import type { Scenario } from "./types";

const scenario: Scenario = {
  id: "c2-beaconing",
  title: "Beaconing a servidor de comando y control",
  severity: "critical",
  description: "Zeek y Suricata detectaron conexiones HTTPS periódicas desde srv-app-01 hacia una IP externa no registrada. Las conexiones ocurren cada 60 segundos con patrón de beaconing consistente, indicando posible malware C2 activo.",
  alertSource: "Zeek + Suricata SID 2024875",
  alertTime: "2026-08-24 11:30:00 UTC",
  logs: [
    { line: 1, timestamp: "Aug 24 10:00:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 2, timestamp: "Aug 24 10:01:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 3, timestamp: "Aug 24 10:02:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 4, timestamp: "Aug 24 10:03:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 5, timestamp: "Aug 24 10:04:00", source: "srv-app-01 nginx.access", message: "GET /api/health 200 — 10.10.2.44 — Lucía Fernández Dev", severity: "info", flagged: false },
    { line: 6, timestamp: "Aug 24 10:04:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 7, timestamp: "Aug 24 10:05:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 8, timestamp: "Aug 24 10:06:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 42% — RAM 58% — Disk 70%", severity: "info", flagged: false },
    { line: 9, timestamp: "Aug 24 10:06:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 10, timestamp: "Aug 24 10:07:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 11, timestamp: "Aug 24 10:08:00", source: "srv-app-01 nginx.access", message: "POST /api/payments/process 201 — 10.10.3.22 — Carlos Ruiz Corp", severity: "info", flagged: false },
    { line: 12, timestamp: "Aug 24 10:08:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 13, timestamp: "Aug 24 10:09:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 14, timestamp: "Aug 24 10:10:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 44% — RAM 59% — Disk 70%", severity: "info", flagged: false },
    { line: 15, timestamp: "Aug 24 10:10:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 16, timestamp: "Aug 24 10:11:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 17, timestamp: "Aug 24 10:12:00", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 18, timestamp: "Aug 24 10:12:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 19, timestamp: "Aug 24 10:13:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 20, timestamp: "Aug 24 10:14:00", source: "srv-app-01 nginx.access", message: "GET /dashboard 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 21, timestamp: "Aug 24 10:14:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 22, timestamp: "Aug 24 10:15:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 23, timestamp: "Aug 24 10:16:00", source: "srv-monitor cron", message: "Metric aggregation: 10,445 events — avg latency 15ms", severity: "info", flagged: false },
    { line: 24, timestamp: "Aug 24 10:16:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 25, timestamp: "Aug 24 10:17:00", source: "srv-web-01 node.app", message: "Queue processor: 143 jobs completed, 21 pending", severity: "info", flagged: false },
    { line: 26, timestamp: "Aug 24 10:17:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 27, timestamp: "Aug 24 10:18:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 28, timestamp: "Aug 24 10:19:00", source: "srv-app-01 nginx.access", message: "POST /api/auth/refresh 200 — 10.10.3.10 — Sofía Ramírez Ops", severity: "info", flagged: false },
    { line: 29, timestamp: "Aug 24 10:19:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 30, timestamp: "Aug 24 10:20:00", source: "srv-app-01 node.app", message: "SSL certificate renewal check — expires in 23 days", severity: "info", flagged: false },
    { line: 31, timestamp: "Aug 24 10:20:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 32, timestamp: "Aug 24 10:21:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 33, timestamp: "Aug 24 10:22:00", source: "srv-web-01 sshd[22701]", message: "Accepted publickey for lucia from 10.10.2.44 port 50401 ssh2", severity: "info", flagged: false },
    { line: 34, timestamp: "Aug 24 10:22:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 35, timestamp: "Aug 24 10:23:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 36, timestamp: "Aug 24 10:24:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 48% — RAM 62% — Disk 71%", severity: "info", flagged: false },
    { line: 37, timestamp: "Aug 24 10:24:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 38, timestamp: "Aug 24 10:25:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 39, timestamp: "Aug 24 10:26:00", source: "srv-web-01 nginx.access", message: "GET /api/products?page=2 200 — 10.10.2.44 — Lucía Fernández Dev", severity: "info", flagged: false },
    { line: 40, timestamp: "Aug 24 10:26:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 41, timestamp: "Aug 24 10:27:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 42, timestamp: "Aug 24 10:28:00", source: "srv-web-01 nginx.access", message: "POST /api/reports/generate 202 — 10.10.1.15 — Martin Gonzalez Admin", severity: "info", flagged: false },
    { line: 43, timestamp: "Aug 24 10:28:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 44, timestamp: "Aug 24 10:29:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 45, timestamp: "Aug 24 10:30:00", source: "srv-app-01 node.app", message: "Cache hit ratio: 89.3% — Redis memory: 389MB/512MB", severity: "info", flagged: false },
    { line: 46, timestamp: "Aug 24 10:30:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 47, timestamp: "Aug 24 10:31:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 48, timestamp: "Aug 24 10:32:00", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=198.51.100.88 DST=10.10.1.10 PROTO=TCP SPT=2222 DPT=22", severity: "info", flagged: false },
    { line: 49, timestamp: "Aug 24 10:32:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 50, timestamp: "Aug 24 10:33:00", source: "srv-monitor alert", message: "srv-app-01: SSL anomaly — 50 connections to cdn-analytics.io (45.77.65.211) in 33 minutes — periodic beaconing detected", severity: "critical", flagged: true },
    { line: 51, timestamp: "Aug 24 10:33:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 52, timestamp: "Aug 24 10:34:00", source: "srv-web-01 sshd[22710]", message: "Accepted publickey for sofia from 10.10.3.10 port 50501 ssh2", severity: "info", flagged: false },
    { line: 53, timestamp: "Aug 24 10:34:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 54, timestamp: "Aug 24 10:35:00", source: "srv-app-01 node.app", message: "Worker process restarted — PID 29102 — config reloaded", severity: "info", flagged: false },
    { line: 55, timestamp: "Aug 24 10:35:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 56, timestamp: "Aug 24 10:36:00", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.1.15 — Martin Gonzalez Admin", severity: "info", flagged: false },
    { line: 57, timestamp: "Aug 24 10:36:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 58, timestamp: "Aug 24 11:30:00", source: "suricata alert", message: "[2024875] SSL/TLS connection to suspicious IP 45.77.65.211 from srv-app-01 (10.10.5.30) — C2 beaconing pattern confirmed", severity: "critical", flagged: true },
  ],
  playbook: [],
  steps: [
    {
      id: "identify",
      title: "Paso 1 — Identificar los logs relevantes",
      description: "Revisá el log de conexiones SSL. ¿Qué patrón ves en las conexiones a cdn-analytics.io?",
      hint: "Fijate en la frecuencia, el IP de destino, y el JA3 hash.",
      options: [
        {
          id: "a",
          label: "Conexiones normales de CDN — srv-app-01 está descargando assets",
          correct: false,
          explanation: "Un CDN real tiene múltiples IPs, TTL variables, y no genera 50 conexiones idénticas cada 60 segundos al mismo IP con el mismo JA3. Este patrón es beaconing C2, no tráfico de CDN.",
          consequence: "En un SOC real, ignorar beaconing C2 como 'tráfico de CDN' permite que el malware siga comunicándose con el atacante, recibiendo comandos y exfiltrando datos silenciosamente.",
        },
        {
          id: "b",
          label: "Beaconing C2 — conexiones periódicas cada 60 segundos al mismo IP con JA3 consistente",
          correct: true,
          explanation: "Correcto. 50+ conexiones al mismo IP (45.77.65.211) cada ~60 segundos, mismo JA3 hash, mismo SNI falso (cdn-analytics.io). El patrón temporal perfecto es Beaconing C2 clásico.",
        },
        {
          id: "c",
          label: "Ruido de red — solo son conexiones SSL normales",
          correct: false,
          explanation: "50 conexiones idénticas en 33 minutos al mismo IP con el mismo JA3 no es ruido. Es un patrón temporal mecánico que indica Beaconing automatizado, no tráfico humano.",
          consequence: "En un SOC real, descartar beaconing C2 como \'ruido\' es uno de los errores más costosos. Cada beacon puede ser un comando del atacante o un paquete de datos robados.",
        },
        {
          id: "d",
          label: "Actualizaciones de software — el servidor está descargando parches",
          correct: false,
          explanation: "Las actualizaciones de software no usan conexiones cada 60 segundos al mismo IP. Los updates van a servidores oficiales (Microsoft, Canonical, etc.), no a IPs desconocidas con SNI falso.",
          consequence: "En un SOC real, confundir beaconing C2 con actualizaciones legítimas es un error grave. Mientras el equipo 'verifica las actualizaciones', el atacante ejecuta comandos remotos en el servidor.",
        },
      ],
    },
    {
      id: "assign",
      title: "Paso 2 — Asignar el incidente",
      description: "¿Quién debería tomar este caso? Un servidor de producción tiene Beaconing C2 activo.",
      hint: "Pensá en qué servidor está afectado y qué nivel de escalamiento requiere.",
      options: [
        {
          id: "a",
          label: "Lucía Fernández (Desarrolladora Backend) — ella trabaja en srv-app-01",
          correct: false,
          explanation: "Lucía desarrolla la aplicación pero no tiene experiencia en respuesta a incidentes de seguridad. Podría ayudar a entender la aplicación, pero no es la primera línea de respuesta.",
          consequence: "En un SOC real, asignar un incidente C2 a un desarrollador sin formación en seguridad resulta en respuestas lentas e incorrectas. Ella puede Help entender la app, pero no puede bloquear IPs o aislar servidores.",
        },
        {
          id: "b",
          label: "Diego López (SOC L2) para investigación + Ana Martínez (DevOps) para contención + escalamiento a CISO",
          correct: true,
          explanation: "Correcto. C2 beaconing en srv-app-01 (servidor de pagos) es nivel 3: compromiso activo con potencial de exfiltración. Diego investiga, Ana contiene, CISO es notificado.",
        },
        {
          id: "c",
          label: "Sofía Ramírez (Gerente de Operaciones) — que apruebe las acciones",
          correct: false,
          explanation: "Sofía no es parte de la cadena de respuesta técnica. Su involvement sería posterior para comunicaciones. La contención técnica no necesita aprobación gerencial inmediata.",
          consequence: "En un SOC real, requerir aprobación gerencial para contener C2 activo da al atacante horas extra de acceso. Cada beacon es un comando ejecutado en el servidor de pagos.",
        },
        {
          id: "d",
          label: "El equipo de desarrollo — que revisen el código de la aplicación",
          correct: false,
          explanation: "Revisar código es una acción de remediación a largo plazo, no de contención inmediata. El servidor tiene Beaconing C2 activo y necesita contención ahora, no una revisión de código.",
          consequence: "En un SOC real, priorizar la revisión de código sobre la contención de C2 es como revisar las cerraduras mientras el ladrón sigue dentro de la casa.",
        },
      ],
    },
    {
      id: "playbook",
      title: "Paso 3 — Consultar el playbook",
      description: "El playbook está vacío. ¿Cuál es la PRIMERA acción de contención para un servidor con Beaconing C2?",
      hint: "Pensá en cortar la comunicación con el atacante sin causar downtime.",
      options: [
        {
          id: "a",
          label: "Apagar srv-app-01 inmediatamente",
          correct: false,
          explanation: "Apagar un servidor de pagos en producción causa downtime directo y pérdida de ingresos. Además, destruye evidencia en memoria. La contención debe ser quirúrgica.",
          consequence: "En un SOC real, apagar un servidor de pagos causa pérdidas financieras por cada minuto de downtime, más daño reputacional con clientes que dependen del servicio.",
        },
        {
          id: "b",
          label: "Bloquear la IP 45.77.65.211 en el firewall perimetral y aislar srv-app-01 de la red externa",
          correct: true,
          explanation: "Correcto. La primera acción es cortar la comunicación C2 bloqueando la IP del atacante. Luego se aisla el servidor de la red externa mientras se investiga. El servicio interno se mantiene si es posible.",
        },
        {
          id: "c",
          label: "Reiniciar srv-app-01 para limpiar la memoria",
          correct: false,
          explanation: "Reiniciar puede eliminar el malware de la memoria temporalmente, pero sin aislar la IP C2, el malware se reactivará al reiniciar. Además, se pierde evidencia volátil en memoria.",
          consequence: "En un SOC real, reiniciar sin contención es inútil: el malware se re-descarga del C2 al reiniciar, y se pierde la evidencia de memoria que podría contener las credenciales del atacante.",
        },
        {
          id: "d",
          label: "Cambiar las credenciales de todos los usuarios del servidor",
          correct: false,
          explanation: "Cambiar credenciales no detiene la comunicación C2. El malware tiene su propio mecanismo de comunicación que no depende de credenciales de usuario. Primero se corta la comunicación.",
          consequence: "En un SOC real, cambiar credenciales sin cortar la conexión C2 es inútil: el malware sigue comunicándose con el atacante mientras 'rotás' contraseñas que no tiene relación con el canal C2.",
        },
      ],
    },
    {
      id: "classify",
      title: "Paso 4 — Clasificar la alerta",
      description: "¿Cuál es la clasificación correcta de este incidente?",
      hint: "Considerá: beaconing periódico, IP no registrada, servidor de pagos, JA3 consistente.",
      options: [
        {
          id: "a",
          label: "Falso positivo — puede ser tráfico legítimo de analytics",
          correct: false,
          explanation: "cdn-analytics.io no está registrado en el asset inventory. El dominio es falso y el IP (45.77.65.211) no pertenece a ningún proveedor de analytics conocido. 50 conexiones cada 60 segundos no es tráfico legítimo.",
          consequence: "En un SOC real, clasificar beaconing C2 como 'analytics legítimo' permite que el atacante siga ejecutando comandos remotos en el servidor de pagos, potencialmente robando datos de tarjetas de crédito.",
        },
        {
          id: "b",
          label: "Positivo verdadero — Beaconing C2 confirmado con potencial de exfiltración",
          correct: true,
          explanation: "Correcto. IP no registrada + dominio falso + patrón temporal mecánico (60s) + JA3 consistente + servidor de pagos = C2 beaconing confirmado con riesgo alto de exfiltración.",
        },
        {
          id: "c",
          label: "Requiere más análisis — necesitamos ver qué datos se transfirieron",
          correct: false,
          explanation: "La clasificación no requiere ver los datos transferidos. El beaconing C2 ya confirma compromiso activo. Los datos transferidos se investigan DURANTE la fase de contención, no para decidir si es real.",
          consequence: "En un SOC real, pedir evidencia de exfiltración antes de clasificar como positivo es un error: mientras buscás 'prueba de exfiltración', el atacante sigue exfiltrando datos cada 60 segundos.",
        },
      ],
    },
    {
      id: "writeup",
      title: "Paso 5 — Redacción del reporte",
      description: "Escribí el reporte del incidente. ¿Cuál es la redacción correcta?",
      hint: "Incluí: beaconing, IP C2, dominio falso, servidor afectado, y acciones.",
      options: [
        {
          id: "a",
          label: "srv-app-01 tiene conexiones raras. Hay que revisar el servidor.",
          correct: false,
          explanation: "Demasiado vago. No menciona la IP C2, el dominio falso, el patrón temporal, ni las acciones de contención necesarias.",
          consequence: "En un SOC real, un reporte así no permite ninguna acción de contención. El equipo no sabe qué IP bloquear, qué servidor aislar, ni qué dominio monitorear.",
        },
        {
          id: "b",
          label: "Beaconing C2 detectado en srv-app-01 (10.10.5.30) hacia 45.77.65.211:443 (SNI: cdn-analytics.io — dominio no registrado). 50+ conexiones SSL cada 60 segundos entre 10:00-11:30 UTC. JA3 hash consistente: a0e9f5d64349fb13191bc781f81f42e1. Servidor de pagos en producción. Impacto NIVEL 3: posible compromiso de datos de clientes. Acciones requeridas: bloquear 45.77.65.211 en firewall perimetral, aislar srv-app-01 de red externa, forense de memoria (RAM dump), revisar procesos activos, verificar integridad de datos de pagos.",
          correct: true,
          explanation: "Reporte completo: QUÉ (beaconing C2), DESDE DÓNDE (srv-app-01), HACIA DÓNDE (IP + dominio falso), PATRÓN (50+ conexiones cada 60s), JA3, SERVIDOR AFECTADO (pagos), IMPACTO, y ACCIONES concretas. Formato profesional SOC.",
        },
        {
          id: "c",
          label: "El servidor está hackeado y se está comunicando con un exterior. Hay que apagarlo.",
          correct: false,
          explanation: "Lenguaje alarmista sin datos técnicos. No hay IP, timestamp, patrón, ni plan de acción. 'Apagarlo' es una medida drástica sin análisis.",
          consequence: "En un SOC real, este tipo de reporte genera pánico y decisiones erróneas como apagar servidores críticos de producción sin forense previo.",
        },
      ],
    },
    {
      id: "return",
      title: "Paso 6 — Volver al panel",
      description: "Incidente documentado y escalado. ¿Qué sigue en tu flujo de trabajo?",
      hint: "Pensá en qué queda pendiente mientras otros equipos ejecutan la contención.",
      options: [
        {
          id: "a",
          label: "Cerrar el caso — ya está todo documentado",
          correct: false,
          explanation: "Un caso de C2 beaconing no se cierra sin verificar que la IP fue bloqueada, el servidor aislado, y el forense de memoria completado.",
          consequence: "En un SOC real, cerrar sin verificar que la IP C2 fue bloqueada significa que el atacante sigue comunicándose con el servidor mientras el equipo cree que 'ya está resuelto'.",
        },
        {
          id: "b",
          label: "Volver al panel de logs para monitorear si hay más servidores con Beaconing C2 mientras DevOps ejecuta la contención",
          correct: true,
          explanation: "Correcto. Tu rol es vigilancia continua: ¿hay más servidores comprometidos? ¿el atacante tiene otros puntos de acceso? ¿la contención está funcionando? Mientras Ana ejecuta, vos monitoreás.",
        },
        {
          id: "c",
          label: "Ir a revisar el servidor físicamente",
          correct: false,
          explanation: "Como SOC analyst, no deberías manipular evidencia físicamente. Eso es trabajo del equipo forense. Tu rol es análisis de logs, clasificación, y monitoreo continuo.",
          consequence: "En un SOC real, tocar el servidor sin protocolo forense puede alterar evidencia y comprometer la cadena de custodia para uso legal.",
        },
      ],
    },
  ],
  summary: "Beaconing C2 detectado en srv-app-01 (10.10.5.30) hacia 45.77.65.211:443 (cdn-analytics.io). 50+ conexiones SSL cada 60 segundos con JA3 consistente. Dominio no registrado en asset inventory. Servidor de pagos en producción. Clasificación: POSITIVO VERDADERO — Beaconing C2 confirmado con riesgo de exfiltración.",
};

export default scenario;
