import type { Scenario } from "./types";

const scenario: Scenario = {
  id: "c2-beaconing",
  title: "Beaconing a servidor de comando y control",
  severity: "critical",
  description: "Zeek y Suricata detectaron conexiones HTTPS periódicas desde srv-app-01 hacia una IP externa no registrada. Las conexiones ocurren cada 60 segundos con patrón de beaconing consistente, indicando posible malware C2 activo.",
  alertSource: "Zeek + Suricata SID 2024875",
  alertTime: "2026-08-24 11:30:00 UTC",
  logs: [
    { line: 1, timestamp: "Aug 24 10:00:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 2, timestamp: "Aug 24 10:01:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 3, timestamp: "Aug 24 10:02:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 4, timestamp: "Aug 24 10:03:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 5, timestamp: "Aug 24 10:04:00", source: "srv-app-01 nginx.access", message: "GET /api/health 200 — 10.10.2.44 — Lucía Fernández Dev", severity: "info", flagged: false },
    { line: 6, timestamp: "Aug 24 10:04:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 7, timestamp: "Aug 24 10:05:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 8, timestamp: "Aug 24 10:06:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 42% — RAM 58% — Disk 70%", severity: "info", flagged: false },
    { line: 9, timestamp: "Aug 24 10:06:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 10, timestamp: "Aug 24 10:07:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 11, timestamp: "Aug 24 10:08:00", source: "srv-app-01 nginx.access", message: "POST /api/payments/process 201 — 10.10.3.22 — Carlos Ruiz Corp", severity: "info", flagged: false },
    { line: 12, timestamp: "Aug 24 10:08:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 13, timestamp: "Aug 24 10:09:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 14, timestamp: "Aug 24 10:10:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 44% — RAM 59% — Disk 70%", severity: "info", flagged: false },
    { line: 15, timestamp: "Aug 24 10:10:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 16, timestamp: "Aug 24 10:11:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 17, timestamp: "Aug 24 10:12:00", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 18, timestamp: "Aug 24 10:12:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 19, timestamp: "Aug 24 10:13:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 20, timestamp: "Aug 24 10:14:00", source: "srv-app-01 nginx.access", message: "GET /dashboard 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 21, timestamp: "Aug 24 10:14:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 22, timestamp: "Aug 24 10:15:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 23, timestamp: "Aug 24 10:16:00", source: "srv-monitor cron", message: "Metric aggregation: 10,445 events — avg latency 15ms", severity: "info", flagged: false },
    { line: 24, timestamp: "Aug 24 10:16:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 25, timestamp: "Aug 24 10:17:00", source: "srv-web-01 node.app", message: "Queue processor: 143 jobs completed, 21 pending", severity: "info", flagged: false },
    { line: 26, timestamp: "Aug 24 10:17:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "info", flagged: false },
    { line: 27, timestamp: "Aug 24 10:18:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 28, timestamp: "Aug 24 10:19:00", source: "srv-app-01 nginx.access", message: "POST /api/auth/refresh 200 — 10.10.3.10 — Sofía Ramírez Ops", severity: "info", flagged: false },
    { line: 29, timestamp: "Aug 24 10:19:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 30, timestamp: "Aug 24 10:20:00", source: "srv-app-01 node.app", message: "SSL certificate renewal check — expires in 23 days", severity: "info", flagged: false },
    { line: 31, timestamp: "Aug 24 10:20:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 32, timestamp: "Aug 24 10:21:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 33, timestamp: "Aug 24 10:22:00", source: "srv-web-01 sshd[22701]", message: "Accepted publickey for lucia from 10.10.2.44 port 50401 ssh2", severity: "info", flagged: false },
    { line: 34, timestamp: "Aug 24 10:22:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 35, timestamp: "Aug 24 10:23:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 36, timestamp: "Aug 24 10:24:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 48% — RAM 62% — Disk 71%", severity: "info", flagged: false },
    { line: 37, timestamp: "Aug 24 10:24:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 38, timestamp: "Aug 24 10:25:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 39, timestamp: "Aug 24 10:26:00", source: "srv-web-01 nginx.access", message: "GET /api/products?page=2 200 — 10.10.2.44 — Lucía Fernández Dev", severity: "info", flagged: false },
    { line: 40, timestamp: "Aug 24 10:26:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 41, timestamp: "Aug 24 10:27:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 42, timestamp: "Aug 24 10:28:00", source: "srv-web-01 nginx.access", message: "POST /api/reports/generate 202 — 10.10.1.15 — Martin Gonzalez Admin", severity: "info", flagged: false },
    { line: 43, timestamp: "Aug 24 10:28:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 44, timestamp: "Aug 24 10:29:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 45, timestamp: "Aug 24 10:30:00", source: "srv-app-01 node.app", message: "Cache hit ratio: 89.3% — Redis memory: 389MB/512MB", severity: "info", flagged: false },
    { line: 46, timestamp: "Aug 24 10:30:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "warning", flagged: true },
    { line: 47, timestamp: "Aug 24 10:31:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 48, timestamp: "Aug 24 10:32:00", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=198.51.100.88 DST=10.10.1.10 PROTO=TCP SPT=2222 DPT=22", severity: "info", flagged: false },
    { line: 49, timestamp: "Aug 24 10:32:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 50, timestamp: "Aug 24 10:33:00", source: "srv-monitor alert", message: "srv-app-01: SSL anomaly — 50 connections to cdn-analytics.io (45.77.65.211) in 33 minutes — periodic beaconing detected", severity: "critical", flagged: true },
    { line: 51, timestamp: "Aug 24 10:33:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 52, timestamp: "Aug 24 10:34:00", source: "srv-web-01 sshd[22710]", message: "Accepted publickey for sofia from 10.10.3.10 port 50501 ssh2", severity: "info", flagged: false },
    { line: 53, timestamp: "Aug 24 10:34:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 54, timestamp: "Aug 24 10:35:00", source: "srv-app-01 node.app", message: "Worker process restarted — PID 29102 — config reloaded", severity: "info", flagged: false },
    { line: 55, timestamp: "Aug 24 10:35:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 56, timestamp: "Aug 24 10:36:00", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.1.15 — Martin Gonzalez Admin", severity: "info", flagged: false },
    { line: 57, timestamp: "Aug 24 10:36:05", source: "srv-app-01 zeek.ssl", message: "Connection: 10.10.5.30 -> 45.77.65.211:443 — SSL established — SNI: cdn-analytics.io — JA3: a0e9f5d64349fb13191bc781f81f42e1", severity: "critical", flagged: true },
    { line: 58, timestamp: "Aug 24 11:30:00", source: "suricata alert", message: "[2024875] SSL/TLS connection to suspicious IP 45.77.65.211 from srv-app-01 (10.10.5.30) — C2 beaconing pattern confirmed", severity: "critical", flagged: true },
  ],
  playbook: [],
  steps: [
    {
      id: "identify",
      title: "Paso 1 — Identificar los logs relevantes",
      description: "Revisá el log de conexiones SSL. ¿Qué patrón ves en las conexiones a cdn-analytics.io?",
      hint: "Fijate en la frecuencia, el IP de destino, y el JA3 hash.",
      options: [
        {
          id: "a",
          label: "Tráfico de keepalive de una aplicación externa — srv-app-01 mantiene sesiones activas con un servicio de terceros",
          correct: false,
          explanation: "El keepalive de aplicaciones legítimas usa intervalos variables (no exactamente cada 60 segundos), múltiples IPs para balanceo de carga, y JA3 hashes diferentes según el endpoint. El patrón mecánico e idéntico indica automatización maliciosa, no keepalive legítimo.",
          consequence: "En un SOC real, catalogar beaconing C2 como keepalive de terceros permite que el atacante siga ejecutando comandos en el servidor de pagos mientras el equipo cree que es tráfico normal de la aplicación.",
        },
        {
          id: "b",
          label: "Conexiones de monitoreo interno — srv-monitor está haciendo health checks periódicos a cdn-analytics.io",
          correct: false,
          explanation: "srv-monitor solo genera health checks a servidores internos (srv-app-01, srv-web-01, srv-db-01). Nunca genera conexiones SSL a IPs externas. Además, los health checks usan HTTP, no HTTPS con JA3 hash consistente.",
          consequence: "En un SOC real, confundir beaconing C2 con monitoreo interno resulta en que el equipo de infraestructura pierda tiempo investigando alertas falsas mientras el atacante mantiene acceso persistente al servidor.",
        },
        {
          id: "c",
          label: "Beaconing C2 — conexiones periódicas cada 60 segundos al mismo IP con JA3 consistente",
          correct: true,
          explanation: "Correcto. 50+ conexiones al mismo IP (45.77.65.211) cada ~60 segundos, mismo JA3 hash, mismo SNI falso (cdn-analytics.io). El patrón temporal perfecto es Beaconing C2 clásico.",
        },
        {
          id: "d",
          label: "cdn-analytics.io no es un dominio de analytics real — el servidor está resolviendo un dominio Typosquatting",
          correct: false,
          explanation: "Aunque cdn-analytics.io no está registrado, Typosquatting implica dominios similares a marcas conocidas para engañar usuarios. Este dominio fue registrado específicamente para C2, no para phishing. La clasificación correcta es beaconing C2, no Typosquatting.",
          consequence: "En un SOC real, clasificar como Typosquatting lleva al equipo de Threat Intel a buscar campañas de phishing en lugar de investigar C2, desperdiciando tiempo crítico de contención.",
        },
      ],
    },
    {
      id: "assign",
      title: "Paso 2 — Asignar el incidente",
      description: "¿Quién debería tomar este caso? Un servidor de producción tiene Beaconing C2 activo.",
      hint: "Pensá en qué servidor está afectado y qué nivel de escalamiento requiere.",
      options: [
        {
          id: "a",
          label: "Diego López (SOC L2) para investigación + Ana Martínez (DevOps) para contención + escalamiento a CISO",
          correct: true,
          explanation: "Correcto. C2 beaconing en srv-app-01 (servidor de pagos) es nivel 3: compromiso activo con potencial de exfiltración. Diego investiga, Ana contiene, CISO es notificado.",
        },
        {
          id: "b",
          label: "Martin Gonzalez (Admin de infraestructura) — que revise la configuración de red del servidor",
          correct: false,
          explanation: "Martin gestiona infraestructura pero no tiene experiencia en respuesta a incidentes de seguridad. Su rol espreventivo, no de contención activa ante C2 beaconing. La investigación forense requiere habilidades específicas de SOC.",
          consequence: "En un SOC real, asignar un incidente C2 a un administrador de infraestructura resulta en respuestas lentas: él puede revisar configuraciones, pero no puede ejecutar contención forense ni clasificar la amenaza correctamente.",
        },
        {
          id: "c",
          label: "Lucía Fernández (Desarrolladora Backend) — ella conoce la aplicación y puede revisar el servidor",
          correct: false,
          explanation: "Lucía desarrolló la aplicación pero no tiene experiencia en respuesta a incidentes de seguridad. Podría entender la app, pero no puede bloquear IPs en firewalls, aislar servidores, ni ejecutar forense de memoria. Además, si hay compromiso interno, podría estar involucrada.",
          consequence: "En un SOC real, asignar un incidente C2 a un desarrollador sin formación en seguridad resulta en respuestas lentas e incorrectas. Ella puede entender la app, pero no puede bloquear IPs o aislar servidores.",
        },
        {
          id: "d",
          label: "El equipo de Threat Intelligence — que analicen la IP 45.77.65.211 en sus feeds",
          correct: false,
          explanation: "Threat Intel puede correlacionar la IP con campañas conocidas, pero su análisis toma tiempo y no ejecuta contención. La prioridad es cortar la comunicación C2 AHORA, no esperar clasificación de inteligencia.",
          consequence: "En un SOC real, priorizar análisis de Threat Intel sobre contención inmediata permite que el atacante siga ejecutando comandos en el servidor de pagos mientras el equipo espera resultados de correlación.",
        },
      ],
    },
    {
      id: "playbook",
      title: "Paso 3 — Consultar el playbook",
      description: "El playbook está vacío. ¿Cuál es la PRIMERA acción de contención para un servidor con Beaconing C2?",
      hint: "Pensá en cortar la comunicación con el atacante sin causar downtime.",
      options: [
        {
          id: "a",
          label: "Aislar srv-app-01 de la red interna pero mantener la conexión externa para capturar tráfico C2",
          correct: false,
          explanation: "Mantener la conexión externa permite que el atacante siga enviando comandos y exfiltrando datos. La primera prioridad es cortar la comunicación C2, no capturar tráfico. El análisis forense se hace después de la contención.",
          consequence: "En un SOC real, intentar capturar tráfico C2 sin bloquear la IP da al atacante acceso continuo al servidor mientras el equipo cree que está recolectando evidencia. Cada segundo es una oportunidad de exfiltración.",
        },
        {
          id: "b",
          label: "Bloquear la IP 45.77.65.211 en el firewall perimetral y aislar srv-app-01 de la red externa",
          correct: true,
          explanation: "Correcto. La primera acción es cortar la comunicación C2 bloqueando la IP del atacante. Luego se aisla el servidor de la red externa mientras se investiga. El servicio interno se mantiene si es posible.",
        },
        {
          id: "c",
          label: "Ejecutar un escaneo de malware completo con antivirus actualizado en srv-app-01",
          correct: false,
          explanation: "Un escaneo de antivirus toma tiempo y puede no detectar malware C2 avanzado que evita firmas conocidas. La prioridad es cortar la comunicación C2 ahora, no esperar a que termine un escaneo.",
          consequence: "En un SOC real, ejecutar un escaneo antivirus como primera acción de contención permite que el malware C2 siga comunicándose mientras el escaneo corre. El atacante puede ejecutar comandos durante toda la duración del análisis.",
        },
        {
          id: "d",
          label: "Rotar las credenciales del servidor y reiniciarlo para limpiar la memoria",
          correct: false,
          explanation: "Rotar credenciales no detiene la comunicación C2. El malware tiene su propio mecanismo de comunicación que no depende de credenciales de usuario. Además, reiniciar puede destruir evidencia volátil en memoria.",
          consequence: "En un SOC real, rotar credenciales y reiniciar sin bloquear la IP C2 es inútil: el malware se re-descarga del C2 al reiniciar, y se pierde la evidencia de memoria que podría contener las credenciales del atacante.",
        },
      ],
    },
    {
      id: "classify",
      title: "Paso 4 — Clasificar la alerta",
      description: "¿Cuál es la clasificación correcta de este incidente?",
      hint: "Considerá: beaconing periódico, IP no registrada, servidor de pagos, JA3 consistente.",
      options: [
        {
          id: "a",
          label: "Positivo falso — cdn-analytics.io es un dominio legítimo de analytics que el equipo de desarrollo configuró",
          correct: false,
          explanation: "cdn-analytics.io no está registrado en el asset inventory de la empresa. Ningún desarrollador puede demostrar que fue configurado. Además, el dominio real no responde a IPs conocidas de proveedores de analytics.",
          consequence: "En un SOC real, clasificar beaconing C2 como positivo falso basándose en la suposición de que el dominio es legítimo permite que el atacante siga ejecutando comandos remotos en el servidor de pagos sin oposición.",
        },
        {
          id: "b",
          label: "Requiere investigación adicional — necesitamos hacer reverse engineering del JA3 hash antes de clasificar",
          correct: false,
          explanation: "El JA3 hash ya está documentado y es consistente. No necesitás reverse engineering para clasificar: 50 conexiones cada 60 segundos al mismo IP con JA3 idéntico es beaconing C2 independientemente de la composición del hash.",
          consequence: "En un SOC real, detenerse a hacer reverse engineering del JA3 mientras hay beaconing activo da al atacante ventaja temporal para ejecutar más comandos y exfiltrar datos del servidor de pagos.",
        },
        {
          id: "c",
          label: "Requiere verificación — necesitamos confirmar con el equipo de desarrollo que cdn-analytics.io no es legítimo",
          correct: false,
          explanation: "El equipo de desarrollo no puede confirmar dominios externos. La verificación se hace contra el asset inventory y los feeds de inteligencia de amenazas. El patrón temporal mecánico ya confirma beaconing C2 sin necesidad de verificar con desarrollo.",
          consequence: "En un SOC real, consultar al equipo de desarrollo para verificar dominios C2 retrasa la contención. Mientras esperan respuesta, el atacante sigue ejecutando comandos en el servidor.",
        },
        {
          id: "d",
          label: "Positivo verdadero — Beaconing C2 confirmado con potencial de exfiltración",
          correct: true,
          explanation: "Correcto. IP no registrada + dominio falso + patrón temporal mecánico (60s) + JA3 consistente + servidor de pagos = C2 beaconing confirmado con riesgo alto de exfiltración.",
        },
      ],
    },
    {
      id: "writeup",
      title: "Paso 5 — Redacción del reporte",
      description: "Escribí el reporte del incidente. ¿Cuál es la redacción correcta?",
      hint: "Incluí: beaconing, IP C2, dominio falso, servidor afectado, y acciones.",
      options: [
        {
          id: "a",
          label: "srv-app-01 muestra conexiones anómalas a IP externa. Se requiere investigación del servidor para determinar si hay compromiso.",
          correct: false,
          explanation: "Demasiado vago para un incidente de C2 beaconing. No incluye la IP del atacante, el dominio falso, el patrón temporal, ni las acciones de contención específicas. Un reporte así no permite ejecutar bloqueo inmediato.",
          consequence: "En un SOC real, un reporte genérico así fuerza al equipo de contención a investigar desde cero, perdiendo tiempo crítico mientras el atacante sigue ejecutando comandos en el servidor de pagos.",
        },
        {
          id: "b",
          label: "srv-app-01 tiene Beaconing C2. Acciones: bloquear IP y revisar procesos del servidor.",
          correct: false,
          explanation: "Incluye la acción correcta pero falta información técnica crítica: dominio falso (cdn-analytics.io), JA3 hash, rango temporal exacto, número de conexiones, y nivel de impacto. Sin esto, el equipo forense no puede replicar la investigación.",
          consequence: "En un SOC real, un reporte sin JA3 hash ni dominio falso impide que el equipo de Threat Intel correlacione el atacante con campañas conocidas y deja sin evidencia para un caso legal.",
        },
        {
          id: "c",
          label: "Beaconing C2 detectado en srv-app-01 (10.10.5.30) hacia 45.77.65.211:443 (SNI: cdn-analytics.io — dominio no registrado). 50+ conexiones SSL cada 60 segundos entre 10:00-11:30 UTC. JA3 hash consistente: a0e9f5d64349fb13191bc781f81f42e1. Servidor de pagos en producción. Impacto NIVEL 3: posible compromiso de datos de clientes. Acciones requeridas: bloquear 45.77.65.211 en firewall perimetral, aislar srv-app-01 de red externa, forense de memoria (RAM dump), revisar procesos activos, verificar integridad de datos de pagos.",
          correct: true,
          explanation: "Reporte completo: QUÉ (beaconing C2), DESDE DÓNDE (srv-app-01), HACIA DÓNDE (IP + dominio falso), PATRÓN (50+ conexiones cada 60s), JA3, SERVIDOR AFECTADO (pagos), IMPACTO, y ACCIONES concretas. Formato profesional SOC.",
        },
        {
          id: "d",
          label: "Compromiso activo en srv-app-01 — servidor de pagos comunicándose con infraestructura adversaria. Aislar inmediatamente y escalar a CISO. Potencialmente datos de clientes expuestos.",
          correct: false,
          explanation: "Mejor tono de urgencia pero carece de datos forenses: no hay IP, JA3, dominio, rango temporal, ni número de conexiones. Sin estos datos, el equipo de contención no puede ejecutar bloqueo específico en firewalls.",
          consequence: "En un SOC real, un reporte sin datos forenses concretos fuerza al equipo a buscar la evidencia original, retrasando la contención activa mientras el atacante mantiene acceso al servidor.",
        },
      ],
    },
    {
      id: "return",
      title: "Paso 6 — Volver al panel",
      description: "Incidente documentado y escalado. ¿Qué sigue en tu flujo de trabajo?",
      hint: "Pensá en qué queda pendiente mientras otros equipos ejecutan la contención.",
      options: [
        {
          id: "a",
          label: "Abrir un ticket de seguimiento para verificar que la remediación se completó en 48 horas",
          correct: false,
          explanation: "El seguimiento de remediación es importante, pero no es la acción inmediata posterior al reporte. La prioridad es monitoreo continuo para detectar movimientos laterales del atacante mientras la contención se ejecuta.",
          consequence: "En un SOC real, enfocarse en seguimiento a largo plazo mientras la contención está activa permite que el atacante exploree otras partes de la red antes de que el equipo detecte movimientos laterales.",
        },
        {
          id: "b",
          label: "Volver al panel de logs para monitorear si hay más servidores con Beaconing C2 mientras DevOps ejecuta la contención",
          correct: true,
          explanation: "Correcto. Tu rol es vigilancia continua: ¿hay más servidores comprometidos? ¿el atacante tiene otros puntos de acceso? ¿la contención está funcionando? Mientras Ana ejecuta, vos monitoreás.",
        },
        {
          id: "c",
          label: "Documentar las lecciones aprendidas del incidente para mejorar el playbook",
          correct: false,
          explanation: "Las lecciones aprendidas se documentan después de cerrar el incidente, no durante la fase activa de contención. Ahora mismo tu prioridad es detectar si hay más servidores comprometidos.",
          consequence: "En un SOC real, documentar lecciones mientras la contención está activa distrae al analista de monitorear movimientos del atacante. El playbook se actualiza después de cerrar el caso, no durante la emergencia.",
        },
        {
          id: "d",
          label: "Contactar al proveedor de CDN para que revise el tráfico que pasa por sus servidores",
          correct: false,
          explanation: "cdn-analytics.io no es un proveedor de CDN legítimo — es un dominio falso registrado por el atacante. Contactar a un proveedor inexistente no tiene sentido y retrasa la vigilancia continua.",
          consequence: "En un SOC real, intentar contactar dominios falso registrados por atacantes desperdicia tiempo crítico de monitoreo mientras el equipo debería estar buscando otros servidores comprometidos.",
        },
      ],
    },
  ],
  summary: "Beaconing C2 detectado en srv-app-01 (10.10.5.30) hacia 45.77.65.211:443 (cdn-analytics.io). 50+ conexiones SSL cada 60 segundos con JA3 consistente. Dominio no registrado en asset inventory. Servidor de pagos en producción. Clasificación: POSITIVO VERDADERO — Beaconing C2 confirmado con riesgo de exfiltración.",
};

export default scenario;
